#!/usr/bin/env python3
"""Count gate for 3d-models: a count in a doc is a claim too.

A number like "29 catalog entries" or "17 registered bets" is a claim about a
set, and every one of them is already computed by something that runs: the
catalog gate prints the entry count, and bikar's `registry:calibration`
generates `.claude/skills/calibrate/bets.md` with the bet and record counts in
its header. Nothing re-ran the hand tally in the doc, so it decayed while
reading as verified.

That is not hypothetical. On 2026-08-03 `docs/backlog.md` §2's count table was
stale by three merges — bets 14 (17), records 16 (17), catalog entries 28 (29),
`.bkr` coupons 5 (8) — and §8's "Counts reconcile" bullet, whose entire job is
to catch that, restated the same wrong figures independently. Fixing §2 and not
§8 would have left two counts disagreeing. **Two sites, one updated, is the
load-bearing failure here**, not an absent number, so it is the case the
self-test asserts.

Rules:

  C1  A marked count equals what its authority prints.
  C2  Every known quantity is marked somewhere, so a quantity cannot quietly
      stop being checked by having its marker deleted.

Marker syntax, written immediately after the number:

    | Entries in the prototype catalog | 29 <!--count:catalog-entries--> | ... |

The comment is invisible in rendered markdown, so marking a number costs the
prose nothing. The gate is **marker-scoped** on purpose, in the same trade
docs_gate.py's D2/D3 make: it cannot know about a count nobody marked, and
guessing at one by regex over prose would fire on sentences it cannot parse.
What it does instead is print the per-quantity site count on every run, so a
quantity asserted in two places and marked in one is visible in the output
rather than silent. That is the same opt-in-with-the-gap-shown shape the
use-case validator uses for anchored pointers.

Usage:
  counts_gate.py [FILE ...]     check the given files (default: docs/**/*.md)
  counts_gate.py --self-test    run the fixtures and verify the gate fires
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GATES = Path(__file__).resolve().parent
BETS = ROOT / ".claude" / "skills" / "calibrate" / "bets.md"

# `29 <!--count:catalog-entries-->` — the number, then the tag naming its
# authority. Whitespace between them is optional so a table cell can be tight.
MARK = re.compile(r"(\d[\d,]*)\s*<!--\s*count:\s*([a-z0-9-]+)\s*-->")

# The generated registry's header line, which is the authority for three of the
# four quantities. Generated by bikar's scripts/gen-calibration-registry.ts —
# reading it rather than recomputing from CAL_BETS is deliberate: two
# independent derivations of one number is how they come to disagree.
BETS_HEADER = re.compile(
    r"\*\*(\d+) registered bets · (\d+) `Calibrated` records — "
    r"\d+ provisional, \d+ measured · (\d+) bets with no record in bikar\.\*\*"
)

CATALOG_SUMMARY = re.compile(r"^catalog models: (\d+) entries;", re.MULTILINE)


def authority_catalog_entries() -> int:
    """However many entries `make validate-catalog` reports."""
    proc = subprocess.run(
        [sys.executable, str(GATES / "catalog_models.py")],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    blob = proc.stdout + proc.stderr
    m = CATALOG_SUMMARY.search(blob)
    if not m:
        raise RuntimeError(
            "catalog_models.py printed no 'catalog models: N entries' summary; "
            f"cannot source catalog-entries from it. Output was:\n{blob}"
        )
    return int(m.group(1))


def authority_bets() -> tuple[int, int, int]:
    if not BETS.exists():
        raise RuntimeError(
            f"{BETS.relative_to(ROOT)} is missing — regenerate it with "
            "`cd ../bikar && npm run registry:calibration`"
        )
    m = BETS_HEADER.search(BETS.read_text(encoding="utf-8"))
    if not m:
        raise RuntimeError(
            f"{BETS.relative_to(ROOT)} has no parseable header line. It is "
            "generated; if its format changed, this gate's BETS_HEADER pattern "
            "must change with it rather than the file being hand-edited."
        )
    return int(m.group(1)), int(m.group(2)), int(m.group(3))


def resolve_authorities() -> dict[str, tuple[int, str]]:
    """Every quantity this gate knows, its current value, and who printed it.

    The set is hard-coded and small on purpose. A gate that discovers its own
    quantities cannot tell a number that vanished from a number that was never
    there, and C2 depends on exactly that distinction.
    """
    bets, records, no_record = authority_bets()
    return {
        "catalog-entries": (
            authority_catalog_entries(),
            "`make validate-catalog`",
        ),
        "cal-bets": (bets, "`.claude/skills/calibrate/bets.md` header"),
        "cal-records": (records, "`.claude/skills/calibrate/bets.md` header"),
        "cal-bets-no-record": (
            no_record,
            "`.claude/skills/calibrate/bets.md` header",
        ),
    }


def marks_in(path: Path) -> list[tuple[int, str, int, str]]:
    """(lineno, quantity, claimed value, the line) for every marker in a file."""
    out = []
    for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        for value, name in MARK.findall(line):
            out.append((n, name, int(value.replace(",", "")), line.strip()))
    return out


def check(
    targets: list[Path], authorities: dict[str, tuple[int, str]]
) -> tuple[list[str], dict[str, int]]:
    findings: list[str] = []
    sites: dict[str, int] = {name: 0 for name in authorities}

    for path in targets:
        for lineno, name, claimed, line in marks_in(path):
            rel = path.relative_to(ROOT)
            if name not in authorities:
                findings.append(
                    f"{rel}:{lineno}: C1 unknown quantity 'count:{name}' — this "
                    f"gate knows {', '.join(sorted(authorities))}. Add an "
                    f"authority for it or drop the marker; a marker with no "
                    f"authority checks nothing while looking like it does."
                )
                continue
            sites[name] += 1
            expected, who = authorities[name]
            if claimed != expected:
                findings.append(
                    f"{rel}:{lineno}: C1 count:{name} says {claimed}, "
                    f"{who} says {expected} — {line[:90]}"
                )

    for name, count in sorted(sites.items()):
        if count == 0:
            expected, who = authorities[name]
            findings.append(
                f"C2 quantity 'count:{name}' is marked nowhere, so nothing "
                f"checks it. {who} currently says {expected}. Either mark the "
                f"place that asserts it, or remove it from this gate — a "
                f"quantity that silently stops being checked is how the tally "
                f"went stale in the first place."
            )
    return findings, sites


FIXTURE_OK = """\
| Entries in the prototype catalog | 29 <!--count:catalog-entries--> | fine |
| Registered bets | 17 <!--count:cal-bets--> | fine |
| Records | 17 <!--count:cal-records--> | fine |
| No record in bikar | 6 <!--count:cal-bets-no-record--> | fine |
"""

# The load-bearing fixture. §2's table is *correct*; the §8 bullet that restates
# the same figure was not updated with it. A gate that only checked the first
# occurrence, or that stopped at the first finding per quantity, would pass this
# — and this is the exact shape of the 2026-08-03 defect.
FIXTURE_ONE_OF_TWO_STALE = """\
| Entries in the prototype catalog | 29 <!--count:catalog-entries--> | correct |
| Registered bets | 17 <!--count:cal-bets--> | correct |
| Records | 17 <!--count:cal-records--> | correct |
| No record in bikar | 6 <!--count:cal-bets-no-record--> | correct |

Reading this file against itself: 28 <!--count:catalog-entries--> print-gated
items = 28 catalog entries. This bullet was not updated with the table above.
"""

FIXTURE_MARKER_DELETED = """\
| Registered bets | 17 <!--count:cal-bets--> | fine |
| Records | 17 <!--count:cal-records--> | fine |
| No record in bikar | 6 <!--count:cal-bets-no-record--> | fine |
"""

FIXTURE_UNKNOWN_QUANTITY = """\
| Entries in the prototype catalog | 29 <!--count:catalog-entries--> | fine |
| Registered bets | 17 <!--count:cal-bets--> | fine |
| Records | 17 <!--count:cal-records--> | fine |
| No record in bikar | 6 <!--count:cal-bets-no-record--> | fine |
| Coupon `.bkr` files | 8 <!--count:bkr-coupon-files--> | nothing prints this |
"""

FAKE = {
    "catalog-entries": (29, "a stub"),
    "cal-bets": (17, "a stub"),
    "cal-records": (17, "a stub"),
    "cal-bets-no-record": (6, "a stub"),
}


def self_test() -> int:
    """Fixed authorities, so the self-test cannot pass by tracking the repo."""
    import tempfile

    cases: list[tuple[str, str, int, str]] = [
        ("clean", FIXTURE_OK, 0, ""),
        ("one-of-two-stale", FIXTURE_ONE_OF_TWO_STALE, 1, "says 28"),
        ("marker-deleted", FIXTURE_MARKER_DELETED, 1, "C2 quantity"),
        ("unknown-quantity", FIXTURE_UNKNOWN_QUANTITY, 1, "unknown quantity"),
    ]

    ok = True
    with tempfile.TemporaryDirectory(dir=ROOT) as tmp:
        for label, body, want, needle in cases:
            path = Path(tmp) / f"{label}.md"
            path.write_text(body, encoding="utf-8")
            findings, _ = check([path], FAKE)
            if len(findings) != want or (needle and needle not in " ".join(findings)):
                ok = False
                print(
                    f"self-test FAIL: {label} wanted {want} finding(s) "
                    f"containing {needle!r}, got {findings}"
                )
            else:
                detail = findings[0].split(": ", 1)[-1][:70] if findings else "clean"
                print(f"self-test ok  : {label} → {detail}")

    # The authorities must actually resolve against the live repo, or the gate
    # is green because it never read anything.
    try:
        live = resolve_authorities()
    except RuntimeError as exc:
        print(f"self-test FAIL: authorities did not resolve — {exc}")
        return 1
    print(
        "self-test ok  : authorities resolve — "
        + ", ".join(f"{k}={v[0]}" for k, v in sorted(live.items()))
    )

    print("self-test:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("files", nargs="*", type=Path)
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    if args.files:
        targets = [p if p.is_absolute() else (ROOT / p) for p in args.files]
    else:
        targets = sorted((ROOT / "docs").rglob("*.md"))
    targets = [p for p in targets if p.exists()]

    try:
        authorities = resolve_authorities()
    except RuntimeError as exc:
        print(f"counts-gate: {exc}", file=sys.stderr)
        return 1

    findings, sites = check(targets, authorities)

    for f in findings:
        print(f, file=sys.stderr)
    summary = ", ".join(f"{k}={sites[k]} site(s)" for k in sorted(sites))
    print(f"counts: {len(targets)} document(s); {summary}")
    if findings:
        print(
            f"\ncounts-gate: {len(findings)} finding(s). Every number here is one "
            "some tool prints — take it from the tool. Override once with "
            "COUNTS_GATE_OK=1 git commit",
            file=sys.stderr,
        )
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
