# https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_OpenSCAD_in_a_command_line_environment
# https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html

SHELL := /bin/bash
ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

# Default openscad lib path: https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Libraries
DEP := ${HOME}/Documents/OpenSCAD/libraries/dotSCAD
# Resolve the OpenSCAD binary across install variants (versioned app, plain app, PATH).
openscad := $(shell \
	for c in \
		/Applications/OpenSCAD-*.app/Contents/MacOS/OpenSCAD \
		/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD \
		$$(command -v openscad); do \
		[ -x "$$c" ] && echo "$$c" && break; \
	done)

# Orbs — 3D-printable Islamic geometric orbs generated by the bikar DSL
# engine (sibling repo). Source of truth is bikar's patterns/Orbs/*.bkr;
# `make orbs` compiles each to a watertight STL (--check runs the
# print-readiness mesh gate), renders its per-symmetry-axis validation
# views, and styles a hero view into a gallery preview PNG. The .bkr
# sources are copied into src/Orbs/ so the gallery's Source links resolve
# in this repo.
# Overridable because the interpreter that runs the gates (stdlib only) is not
# always the one carrying Pillow and PyYAML. On 2026-08-02 `make deploy` failed
# at web-images on a machine where the first python3 on PATH had no PIL and a
# conda env did — and the error said "pip install pillow", which was the wrong
# advice. Point this at the interpreter that has the deps instead:
#   make deploy PYTHON=/path/to/python3
PYTHON ?= python3

# `?=`, not `:=`, so the environment can point this somewhere else without
# putting it on every command line.
BIKAR_DIR ?= ${HOME}/Workspace/git/bikar
BIKAR := node $(BIKAR_DIR)/packages/cli/dist/index.js

# Which bikar commit a render came from is not recoverable after the fact: an
# STL carries no provenance and `build/` is .gitignore'd on master, so the
# only place the answer could live is a stamp written at build time.
#
# The trap is not hypothetical. On 2026-08-02 the default BIKAR_DIR was
# sitting on a *detached HEAD one commit behind `main`* — because `main` was
# checked out in a sibling worktree and a repository cannot hold the same
# branch in two places. `make bricks` would have built from it and said
# nothing. (That build would in fact have been correct; the point is that
# nothing here could have told you either way.)
#
# So: every brick and set build stamps what it built from, the stamp deploys
# beside the images, and the detached/dirty cases are *reported*. Only
# BIKAR_REF fails the build — set it when the answer has to be exact, and
# leave it empty for ordinary local iteration on unpushed bikar work. A gate
# that fired on every dirty tree would be switched off within a week.
BIKAR_REF ?=
ORB_VIEWS := $(ROOT_DIR)/build/orb-views
# Per-orb breakdown: the construction stages plus a swept camera, both written
# by `bikar render --format timelapse`, read by the vendored breakdown.html.
ORB_BREAKDOWN := $(ROOT_DIR)/build/orb-breakdown
# 36 frames, one per 10°. Not a tuned number: the page plays them at 110 ms,
# so 36 is a four-second turn, and the reader who wants a specific angle
# scrubs rather than waits. Raising it costs render time and bytes on every
# orb; lowering it makes the turn read as a flip-book.
ORB_TURNTABLE := 36

# gh-pages deploy
PAGES_BRANCH := gh-pages
PAGES_WORKTREE := $(ROOT_DIR)/.gh-pages
# Recursively expanded, not `:=`, because LAB_PAGES is defined further down
# beside the vendor step that uses it. `:=` here would expand to nothing and
# deploy a gallery with no studio pages in it.
DEPLOY_PATHS = index.html status.html $(LAB_PAGES) assets build/images build/stls build/orb-breakdown build/bikar-ref.txt src LICENSE README.md docs/prints.md prints-manifest.json status-manifest.json

.PHONY: prints-manifest status-manifest validate-status cookie-cutters orbs orb-breakdown-index bikar-stamp bricks coasters coupons validate-coupons pattern-sets lab lego-lab lab-vendor lab-smoke web-images deploy setup-hooks site experiences validate-use-cases use-case-links validate-docs validate-pointers validate-catalog validate-counts validate-timelapse validate-prints validate-constructions validate-hooks validate-branch-guard validate-site-graph site-graph validate validate-strict validate-parity validate-secrets local.ci local.ci-strict local.ci-parity bambu-doctor bambu-discover bambu-typecheck validate-env bambu-flags validate-bambu-flags validate-reflect

# One-time per clone: route git hooks to the tracked .githooks/ dir
# (pre-commit dispatches .githooks/pre-commit.d/: gitleaks secret scan,
# the use-case map guard — see .claude/skills/maintain-use-cases/ — then the
# design-doc gate, see .claude/gates/docs_gate.py; then the site-graph gate,
# see .claude/gates/site_graph.py).
setup-hooks:
	git -C ${ROOT_DIR} config core.hooksPath .githooks
	@echo "hooks: core.hooksPath -> .githooks"
	@# Listed, not enumerated by hand: the hand-written version of this line
	@# named four hooks while the directory held seven.
	@echo "  pre-commit.d = $$(ls ${ROOT_DIR}/.githooks/pre-commit.d | tr '\n' ' ')"
	@echo "  pre-push     = gitleaks full history (this repo has no CI)"
	@echo "  run them all over the whole tree, any time: make validate"
	@echo "                     (or 'make local.ci', the sibling repos' spelling)"
	@if ! command -v gitleaks >/dev/null 2>&1; then \
		echo "  WARNING: gitleaks not installed — commits AND pushes will block."; \
		echo "           brew install gitleaks   (override: GITLEAKS_OK=1)"; \
	fi

# Validate the actor/use-case map's hash-pinned code pointers.
validate-use-cases:
	@$(PYTHON) -c "import yaml" 2>/dev/null || { \
		echo "PyYAML required, and $$($(PYTHON) -c 'import sys;print(sys.executable)') does not have it."; \
		echo "  install it there:  $(PYTHON) -m pip install pyyaml"; \
		echo "  or use one that does:  make $@ PYTHON=/path/to/python3"; \
		exit 1; }
	$(PYTHON) ${ROOT_DIR}/.claude/skills/maintain-use-cases/validate.py

# Clickable editor links for every validated line pointer, in this repo's docs
# and in the map. Generated on demand and never committed: the URL needs an
# absolute path, and an absolute path is a claim about one laptop — which is why
# doc_pointers.py rejects `/Users/...` outright. Validation runs first and a
# failure prints no links, because a clickable link to a line the tool knows is
# wrong is worse than no link at all.
use-case-links:
	@$(PYTHON) ${ROOT_DIR}/.claude/skills/maintain-use-cases/validate.py --links

# Design-doc gate: dead relative links (D1/K9), validators shipped without
# asserted PASS+FAIL examples (D2/K6), defaults with no citation or CAL-* bet
# id (D3/K4). Rules and the measurement behind them:
# docs/grounding-defect-taxonomy.md. `self-test` runs the gate's own fixtures.
validate-docs:
	$(PYTHON) ${ROOT_DIR}/.claude/gates/docs_gate.py --self-test
	$(PYTHON) ${ROOT_DIR}/.claude/gates/docs_gate.py

# Doc-pointer gate: every backticked path in CLAUDE.md, .claude/skills/**,
# .claude/gates/** and docs/** must name a file that exists — here, in a sibling
# repo (resolved against a git ref, never someone else's working tree), or in
# .claude/gates/doc-pointer-baseline.json with a stated reason. Ported from
# bikar's scripts/check-doc-pointers.ts; the transfer conditions and what
# deliberately did *not* transfer are in the gate's module docstring.
validate-pointers:
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/doc_pointers.py --self-test
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/doc_pointers.py

# Catalog<->model gate: every --param / --piece / --brick-fit a prototype-catalog
# entry prescribes must name something its .bkr actually declares. The
# declaration keywords and the BrickFit field set are harvested from bikar
# (docs/grammar.md, kernel3d/lego.ts) rather than listed here, and the gate says
# so out loud if either becomes unreadable instead of quietly passing.
validate-catalog:
	BIKAR_DIR=$(BIKAR_DIR) python3 ${ROOT_DIR}/.claude/gates/catalog_models.py --self-test
	BIKAR_DIR=$(BIKAR_DIR) python3 ${ROOT_DIR}/.claude/gates/catalog_models.py

# Count gate: a number in a doc is a claim about a set. Each `<!--count:NAME-->`
# tag pins the written number to the tool that prints it — the catalog gate for
# entry counts, the generated .claude/skills/calibrate/bets.md for bet and
# record counts. `self-test` runs against fixed stub authorities, so it cannot
# pass by tracking whatever the repo happens to say; its load-bearing fixture is
# a doc whose table is right and whose second, restating site is stale.
validate-counts:
	$(PYTHON) ${ROOT_DIR}/.claude/gates/counts_gate.py --self-test
	$(PYTHON) ${ROOT_DIR}/.claude/gates/counts_gate.py

# Timelapse gate: the breakdown page's invariants live *across* files — one
# viewBox over three sequences, a byte identity at each junction between them,
# and a last stage frame that is the very drawing qiyas scores. None of them
# can be seen in a single file, and each is broken by an edit that looks local.
# `--self-test` builds a clean fixture, requires it to come back clean, then
# mutates it once per rule and requires each mutation to fire.
validate-timelapse:
	$(PYTHON) ${ROOT_DIR}/.claude/gates/timelapse_gate.py --self-test
	$(PYTHON) ${ROOT_DIR}/.claude/gates/timelapse_gate.py

# Prints gate: a print-run record under docs/prints/ pins the geometry it
# printed (R1, re-resolved against bikar at the recorded commit), proves its
# photos exist and are unique across every record (R2), and prints how many
# records it checked so an empty tree reads as "0 records checked", never a
# false green (R4). Design: docs/prints-tab-design.md §7. `--self-test` builds a
# clean fixture, requires it clean, then mutates it once per rule and requires
# each to fire. Ships before the first plate on purpose: R4's visible count is
# what makes wiring the gate at zero records honest rather than broken-looking.
validate-prints: prints-manifest
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/prints_gate.py --self-test
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/prints_gate.py

# `core.hooksPath` is repo-wide, so pre-commit.d/ runs in every worktree of this
# clone — including the `.gh-pages` one `deploy` creates, which tracks .githooks
# and not .claude. This builds that shape and asserts each hook skips instead of
# dying; it is the regression test for a deploy that failed on the gh-pages
# commit with `[Errno 2] No such file or directory`.
#
# The second test covers the other half of "a hook runs in an environment a
# person does not": git exports GIT_DIR to hooks it launches from a linked
# worktree, GIT_DIR outranks -C, and validate.py's root then resolved into
# .claude/skills/. Sibling pointer checks became warn-and-skip, so the hook
# checked 52 of 119 pointers and exited 0 while the hand-run printed "all valid".
validate-hooks:
	${ROOT_DIR}/.githooks/tests/worktree-without-claude.sh
	${ROOT_DIR}/.githooks/tests/hook-env-git-dir.sh

# Site-graph gate: docs/site-graph.json declares every page this project
# publishes, every link between them, and each host's exposure. The gate holds
# that declaration to the repo. It never asks whether a URL resolves — four
# crawler runs on 2026-08-02 reported the one real defect as green, because
# Cloudflare Access answers an unauthenticated request with HTTP 200. Reasoning:
# docs/site-graph.md; survey: docs/research/sitemap-link-graph-survey.md.
# `self-test` mutates the real graph in memory and requires each defect to fire.
validate-site-graph:
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/site_graph.py --self-test
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/site_graph.py

# Full-history secret scan — the wholesale form of .githooks/pre-commit.d/
# 10-gitleaks, which sees staged hunks only. Same command .githooks/pre-push
# runs; `gitleaks git`, not the deprecated `detect`. This existed as a hook and
# a pre-push line but never as a target, which is precisely the asymmetry that
# made `validate` unwritable as a hand-listed chain — see hook_parity.py.
validate-secrets:
	@command -v gitleaks >/dev/null 2>&1 || { \
		echo "gitleaks not installed — brew install gitleaks"; exit 1; }
	gitleaks git ${ROOT_DIR} --no-banner --redact --verbose

# Run every pre-commit gate over the WHOLE TREE, in the order the dispatcher
# runs them, plus the checks that have no hook behind them. This repo has no
# CI, so the hooks are the gate set and this is the only way to ask "would all
# of it pass right now?" without staging something.
#
# The list is not written here. Each hook declares its own wholesale form in a
# `# wholesale:` line, and `hook_parity.py --check` fails on a hook that
# declares none — so a hook added tomorrow cannot quietly fall out of this
# target. Measured 2026-08-17: at the moment this was written the hook set and
# the validate-* target set were not subset-related in either direction, so a
# chain typed by hand would have shipped wrong. Anything that could not be
# verified (a missing tool) is named in the summary line, never dropped.
validate:
	@$(PYTHON) ${ROOT_DIR}/.claude/gates/hook_parity.py --self-test
	@BIKAR_DIR=$(BIKAR_DIR) PYTHON=$(PYTHON) $(PYTHON) -u ${ROOT_DIR}/.claude/gates/hook_parity.py --run

# As `validate`, but "could not verify" is a failure. For a release or a deploy,
# where a skipped gate must not read as a pass.
validate-strict:
	@$(PYTHON) ${ROOT_DIR}/.claude/gates/hook_parity.py --self-test
	@BIKAR_DIR=$(BIKAR_DIR) PYTHON=$(PYTHON) $(PYTHON) -u ${ROOT_DIR}/.claude/gates/hook_parity.py --run --strict

# Just the coverage claim — instant, no gates run. What the hook checks.
validate-parity:
	@$(PYTHON) ${ROOT_DIR}/.claude/gates/hook_parity.py --self-test
	@$(PYTHON) ${ROOT_DIR}/.claude/gates/hook_parity.py --check

# One name across four repos. bikar, qiyas and sacred-patterns each spell this
# `make local.ci` / `local.ci-strict` / `local.ci-parity`; here the same three
# checks are `validate*`, because here they are hooks rather than workflows.
# That distinction is real and the docs keep it — but it is not worth making
# somebody who just ran `make local.ci` in a sibling repo go and read a Makefile
# to find out this one calls it something else. Aliases, not copies: one
# definition, four spellings of its front door.
local.ci: validate
local.ci-strict: validate-strict
local.ci-parity: validate-parity

# Regenerate the ```mermaid block in docs/site-graph.md from the JSON, then
# re-check — so a hand-edited render cannot outlive the graph it renders.
site-graph:
	$(PYTHON) ${ROOT_DIR}/.claude/gates/site_graph.py --update-doc
	$(MAKE) -C ${ROOT_DIR} validate-site-graph

%.png: %.scad
	@echo Generating $*.png from $@
	${openscad} -o ${ROOT_DIR}/build/images/$$(basename $*.png) $*.scad

%.stl: %.scad
	@echo Generating $*.stl from $@
	${openscad} -o ${ROOT_DIR}/build/stls/$$(basename $*.stl) $*.scad

cookie-cutters:
	ls ${ROOT_DIR}/src/CookieCutters/*.scad | sed 's/.scad//g' | grep -v Common \
		| xargs -n 1 basename \
		| xargs -n 1 bash -c ' \
			cd ${ROOT_DIR}/src/CookieCutters && make -f ${ROOT_DIR}/Makefile $${0}.png $${0}.stl \
		'
# Each orb's output directories are wiped before they are rewritten, and that
# is the whole fix for a defect that shipped: which drawings an orb produces is
# decided by what it declares, so the set can *shrink* between two versions of
# the engine. Maclado-9-Overlap's bands cross rather than tile, and the
# projector refuses to draw it as cells by design — yet three cell views from
# the run before that refusal sat in build/orb-views/Maclado9Overlap/ for
# weeks, scored by qiyas and picked as the gallery hero, because nothing ever
# removed a file the generator had stopped writing. Regeneration cannot fix a
# file regeneration no longer touches; only deletion can.
#
# `bikar-stamp` is a prerequisite and not a courtesy. DEPLOY_PATHS ships
# build/bikar-ref.txt beside build/stls and build/images -- both written right
# here -- so the stamp is read as "the bikar that produced these". This was the
# one bikar-consuming target that did not depend on it (bricks, coupons and
# pattern-sets all did), so the deployed stamp named whichever commit happened
# to be checked out the last time one of *those* ran. Found on 2026-08-19:
# `make orbs` against a freshly merged bikar left the stamp on the pre-merge
# sha, and every render below it was from the merge.
orbs: bikar-stamp
	@[ -f "$(BIKAR_DIR)/packages/cli/dist/index.js" ] \
		|| { echo "bikar CLI not built — run 'npm run build' in $(BIKAR_DIR)"; exit 1; }
	@command -v rsvg-convert >/dev/null \
		|| { echo "rsvg-convert required: brew install librsvg"; exit 1; }
	@set -euo pipefail; \
	mkdir -p ${ROOT_DIR}/build/stls ${ROOT_DIR}/build/images ${ROOT_DIR}/src/Orbs; \
	for bkr in $(BIKAR_DIR)/patterns/Orbs/*.bkr; do \
		stem=$$(basename "$$bkr" .bkr); name=$${stem//-/}; \
		echo "== $$name"; \
		$(BIKAR) render "$$bkr" --format stl --check -o ${ROOT_DIR}/build/stls/$$name.stl; \
		rm -rf $(ORB_VIEWS)/$$name $(ORB_BREAKDOWN)/$$name; \
		mkdir -p $(ORB_VIEWS)/$$name; \
		if err=$$($(BIKAR) render "$$bkr" --format views -o $(ORB_VIEWS)/$$name 2>&1); then \
			mkdir -p $(ORB_BREAKDOWN)/$$name; \
			$(BIKAR) render "$$bkr" --format timelapse --turntable $(ORB_TURNTABLE) \
				-o $(ORB_BREAKDOWN)/$$name; \
			cp "$$bkr" ${ROOT_DIR}/src/Orbs/; \
		elif printf '%s' "$$err" | grep -q 'has no cell decomposition'; then \
			rm -rf $(ORB_VIEWS)/$$name; \
			echo "   SKIP views+timelapse: $$name is an open-shell wheelfield orb (STL only) — no cell or ribbon views to tile (maclado-lattice doc §4; drawsOrbViews)"; \
		else \
			rm -rf $(ORB_VIEWS)/$$name; \
			printf '%s\n' "$$err" 1>&2; \
			echo "orbs: $$name failed --format views, and not with the recognized no-views refusal (open-shell wheelfield) — round-pattern orbs render a site-scaffold breakdown now (#158), so a 2D-only refusal here is a real regression, not a skip — stopping" 1>&2; \
			exit 1; \
		fi; \
	done; \
	$(MAKE) -C ${ROOT_DIR} orb-breakdown-index; \
	cd ${ROOT_DIR} && $(PYTHON) build/orb_previews.py

# The index breakdown.html reads when it is opened with no `?orb=`. Written
# from what is on disk rather than from the loop above, so an orb whose
# timelapse failed to write a manifest is absent from the picker instead of
# being listed and then 404-ing — the page has a not-found state, and the
# picker is not the place to send someone into it.
#
# It also checks the shape of each manifest, and that check earns its keep:
# `orbs` guards only that bikar's `dist/index.js` *exists*, so a dist built
# before `--turntable` shipped writes 14 perfectly valid breakdown directories
# with no `turntable` and no `source` in any of them. Every page state still
# renders — every one of them the "this orb has no camera sweep" state. That
# happened here on 2026-08-18. `turntable: []` is a real answer (the woven
# orbs draw ribbons, not projected cells, and the generator says so), so the
# claim checked is that the *keys* are there, which a stale dist cannot fake.
#
# That tuple used to be typed here as well as in the gate that checks it after
# the fact — two sites for one list, which is the exact shape `counts_gate.py`
# exists to catch. `timelapse_gate.py --keys` is the single owner now, and this
# target calls it.
orb-breakdown-index:
	@set -euo pipefail; \
	test -d $(ORB_BREAKDOWN) || { echo "no $(ORB_BREAKDOWN) — run 'make orbs'"; exit 1; }; \
	cd $(ORB_BREAKDOWN); \
	orbs=$$(for d in */; do [ -f "$${d}manifest.json" ] && echo "$${d%/}"; done | sort); \
	test -n "$$orbs" || { echo "orb-breakdown-index: no orb wrote a manifest.json"; exit 1; }; \
	$(PYTHON) ${ROOT_DIR}/.claude/gates/timelapse_gate.py --keys $(ORB_BREAKDOWN) >/dev/null; \
	printf '%s\n' "$$orbs" \
		| $(PYTHON) -c 'import json,sys; json.dump({"orbs": sys.stdin.read().split()}, sys.stdout, indent=2)' \
		> index.json; \
	spun=$$(for orb in $$orbs; do $(PYTHON) -c 'import json,sys; print(len(json.load(open(sys.argv[1]+"/manifest.json"))["turntable"]))' "$$orb"; done | grep -cv '^0$$' || true); \
	echo "orb-breakdown-index: $$(echo "$$orbs" | wc -l | tr -d " ") orb(s), $$spun with a camera sweep"

# Bricks — LEGO-compatible pieces from the same bikar engine (Lego Lab
# design §10 P0). Same shape as `orbs`, with one difference that is worth
# stating: an orb's preview comes from its per-symmetry-axis validation
# views, and a brick has none — there is no brick view set and no recorded
# qiyas composite, so a brick's claim is made by its two grid gates and the
# mesh gate, not by a render. build/brick_previews.py therefore draws the
# mesh itself, via OpenSCAD import(), which lands gold-on-cream exactly
# where `make web-images` expects it.
# Records which bikar produced the renders that follow. See BIKAR_REF above.
bikar-stamp:
	@set -eu; \
	sha=$$(git -C "$(BIKAR_DIR)" rev-parse HEAD); \
	ref=$$(git -C "$(BIKAR_DIR)" rev-parse --abbrev-ref HEAD); \
	dirty=$$(git -C "$(BIKAR_DIR)" status --porcelain | head -1); \
	if [ -n "$(BIKAR_REF)" ]; then \
		want=$$(git -C "$(BIKAR_DIR)" rev-parse "$(BIKAR_REF)^{commit}"); \
		[ "$$sha" = "$$want" ] \
			|| { echo "BIKAR_REF wants $(BIKAR_REF) ($$want) but $(BIKAR_DIR) is at $$sha"; exit 1; }; \
	fi; \
	mkdir -p ${ROOT_DIR}/build; \
	printf '%s %s%s\n' "$$sha" "$$ref" "$${dirty:+ +dirty}" > ${ROOT_DIR}/build/bikar-ref.txt; \
	echo "== bikar $$sha ($$ref)"; \
	[ -z "$$dirty" ] || echo "   note: working tree is dirty — the stamp says so, the STLs cannot"; \
	[ "$$ref" != "HEAD" ] || echo "   note: detached HEAD — this is not a branch tip"

bricks: bikar-stamp
	@[ -f "$(BIKAR_DIR)/packages/cli/dist/index.js" ] \
		|| { echo "bikar CLI not built — run 'npm run build' in $(BIKAR_DIR)"; exit 1; }
	@[ -d "$(BIKAR_DIR)/patterns/Lego" ] \
		|| { echo "no patterns/Lego in $(BIKAR_DIR) — the brick presets live on bikar's lego-lab work; override with 'make bricks BIKAR_DIR=...'"; exit 1; }
	@set -euo pipefail; \
	mkdir -p ${ROOT_DIR}/build/stls ${ROOT_DIR}/build/images ${ROOT_DIR}/src/Lego; \
	: > ${ROOT_DIR}/build/.brick-names; \
	for bkr in $(BIKAR_DIR)/patterns/Lego/*.bkr; do \
		if grep -q '^mural ' "$$bkr"; then continue; fi; \
		stem=$$(basename "$$bkr" .bkr); name=$${stem//-/}; \
		echo "== $$name"; \
		$(BIKAR) render "$$bkr" --format stl --check -o ${ROOT_DIR}/build/stls/$$name.stl; \
		echo "$$name" >> ${ROOT_DIR}/build/.brick-names; \
		cp "$$bkr" ${ROOT_DIR}/src/Lego/; \
	done; \
	cd ${ROOT_DIR} && $(PYTHON) build/brick_previews.py

# Coupons — the machine card (docs/calibration-design.md), 23 rungs that
# measure a printer rather than print a thing. Deliberately NOT shaped like
# `orbs`/`bricks`, which loop over a directory and render each file whole:
# this is one .bkr holding 26 pieces, and §6 is explicit that omitting
# `--piece` renders the file's last solid — a plate and a loose pin fused in
# one STL, "a valid render and a useless coupon".
#
# The rung list, the per-rung flags and the expected results are not repeated
# here. They are read out of the design doc itself by build/verify_machine_card.py,
# which renders each rung and diffs the mesh gate against §7's table — so a
# doc edit and a geometry change cannot drift apart silently. Four rungs are
# expected to FAIL the feature floor (that is what MC-2's wall ladder is for),
# and the verifier asserts those failures rather than skipping them.
# `--self-test` mutates the doc seven ways and checks the gate fires each time.
coupons: bikar-stamp
	@[ -f "$(BIKAR_DIR)/packages/cli/dist/index.js" ] \
		|| { echo "bikar CLI not built — run 'npm run build' in $(BIKAR_DIR)"; exit 1; }
	@$(PYTHON) ${ROOT_DIR}/build/verify_machine_card.py --bikar-dir "$(BIKAR_DIR)"

validate-coupons:
	@$(PYTHON) ${ROOT_DIR}/build/verify_machine_card.py --bikar-dir "$(BIKAR_DIR)" --self-test

# Photo map — a top-down render of a sliced plate with the coupons to photograph
# ringed, the visual index of `prototype`'s per-coupon photograph checklist. The
# *what to shoot* set is data (a JSON sidecar next to the bench sheet), not code,
# so the same target serves any plate: override PLATE / HL / PHOTO_MAP. Reads the
# gitignored sliced .3mf under build/, so slice the plate first (`bambu slice`).
PLATE ?= ${ROOT_DIR}/build/stls/coupons/machine-card/plate-1-machine-card.sliced.3mf
HL ?= ${ROOT_DIR}/docs/prints/plate-1-photo-map.json
PHOTO_MAP ?= ${ROOT_DIR}/docs/prints/plate-1-photo-map.png
CONTACT_SHEET ?= ${ROOT_DIR}/docs/prints/plate-1-contact-sheet.png
plate-photo-map:
	@[ -f "$(PLATE)" ] \
		|| { echo "sliced plate not found: $(PLATE) — slice it first (bambu slice plate ...)"; exit 1; }
	@$(PYTHON) ${ROOT_DIR}/build/plate_photo_map.py "$(PLATE)" "$(HL)" "$(PHOTO_MAP)" \
		--contact-sheet "$(CONTACT_SHEET)"

# Pattern sets — mural presets from the same directory, skipped by `bricks`
# above because one STL is the wrong shape for them twice over: a mural
# prints as one gated STL *per piece*, and the single-mesh `--check` path
# holds the fused panel to the orb floor (1.2 mm) when every piece was
# already gated at the brick floor (0.7 mm) it is entitled to — measured
# here 2026-08-02: Star-Mural's fused mesh FAILs at minFeature 0.76 mm
# while all four of its pieces PASS. So two renders per set: `--format
# parts --check` writes the print files into build/stls/<name>/, and an
# ungated `--format stl` writes the composed panel — every piece at its
# layout offset — which is the honest gallery image, because the thing the
# set promises is the reconstituted pattern, not one fragment.
pattern-sets: bikar-stamp
	@[ -f "$(BIKAR_DIR)/packages/cli/dist/index.js" ] \
		|| { echo "bikar CLI not built — run 'npm run build' in $(BIKAR_DIR)"; exit 1; }
	@[ -d "$(BIKAR_DIR)/patterns/Lego" ] \
		|| { echo "no patterns/Lego in $(BIKAR_DIR) — the mural presets live on bikar's lego-lab work; override with 'make pattern-sets BIKAR_DIR=...'"; exit 1; }
	@set -euo pipefail; \
	mkdir -p ${ROOT_DIR}/build/stls ${ROOT_DIR}/build/images ${ROOT_DIR}/src/Lego; \
	: > ${ROOT_DIR}/build/.set-names; \
	for bkr in $(BIKAR_DIR)/patterns/Lego/*.bkr; do \
		grep -q '^mural ' "$$bkr" || continue; \
		stem=$$(basename "$$bkr" .bkr); name=$${stem//-/}; \
		echo "== $$name (set)"; \
		$(BIKAR) render "$$bkr" --format parts --check -o ${ROOT_DIR}/build/stls/$$name; \
		$(BIKAR) render "$$bkr" --format stl -o ${ROOT_DIR}/build/stls/$$name.stl; \
		echo "$$name" >> ${ROOT_DIR}/build/.set-names; \
		cp "$$bkr" ${ROOT_DIR}/src/Lego/; \
	done; \
	[ -s ${ROOT_DIR}/build/.set-names ] \
		|| { echo "no mural presets in $(BIKAR_DIR)/patterns/Lego — nothing to render"; exit 1; }; \
	cd ${ROOT_DIR} && $(PYTHON) build/brick_previews.py --sets

# The studio — the pages built by bikar's packages/lab (vite) and vendored
# here at the site root, plus the hashed assets/ dir they share. All
# generated, gitignored on master, published by `make deploy`.
#
# One build serves all of them, because each is one of packages/lab's *entries*
# and not a package of its own (Lego Lab design §9). That is also why there is
# one vendor step rather than four: four builds would mean four `rm -rf assets`,
# and each would delete the chunks the previous page had just been linked
# against. `lab` and `lego-lab` are the two names people reach for; they
# share the recipe so `make lab lego-lab` still builds once.
#
# The page list lives here once. It is the deploy-side twin of the catalogue
# bikar checks against its own directory (Lego Lab design §13) — this end
# cannot read that one, so a page added there and not here vendors nothing and
# `lab-smoke` never looks for it. Adding a page is two edits, in two repos, and
# saying so is cheaper than a cross-repo check that would have to run a build.
LAB_PAGES = studio.html lab.html lego.html design.html breakdown.html prints.html coaster.html
# The subset that runs the compile worker. studio.html and design.html render
# from static data, so requiring a worker chunk of them would fail a page that
# is working exactly as designed.
# breakdown.html is here for its "Turn it yourself" handoff: the page plays
# rendered SVG frames with no compile at all, and only recompiles source.bkr in
# the worker when the reader asks for the live mesh.
LAB_WORKER_PAGES = lab.html lego.html breakdown.html coaster.html

lab lego-lab: lab-vendor

lab-vendor:
	@for page in $(LAB_PAGES); do \
		[ -f "$(BIKAR_DIR)/packages/lab/$$page" ] \
			|| { echo "no packages/lab/$$page in $(BIKAR_DIR) — the studio entries live on bikar's lego-lab work; override with 'make lab BIKAR_DIR=...'"; exit 1; }; \
	done
	@set -euo pipefail; \
	cd $(BIKAR_DIR)/packages/lab && npx vite build; \
	for page in $(LAB_PAGES); do \
		cp $(BIKAR_DIR)/packages/lab/dist/$$page ${ROOT_DIR}/$$page; \
	done; \
	rm -rf ${ROOT_DIR}/assets; \
	cp -R $(BIKAR_DIR)/packages/lab/dist/assets ${ROOT_DIR}/assets; \
	$(MAKE) -C ${ROOT_DIR} lab-smoke; \
	echo "Studio vendored: $(LAB_PAGES) + assets/"

# Vendoring smoke (orb-lab-p2-design §4.2): each vendored page and its hashed
# assets must exist and reference each other — a broken copy step or a stale
# assets/ dir fails here, not on the deployed site. Every page is checked,
# because they share one assets/ dir and a rebuild that re-hashed only one
# page's chunks would leave the others pointing at files that no longer exist.
#
# The worker hunt reads *every* js asset a page pulls in, not the first one
# alphabetically. The old version took the first and got away with it only
# while the entry chunk happened to sort first; adding studio/design chunks
# moved a shared chunk to the front and the check failed a page that was
# perfectly well-formed. "First by name" was never the entry module.
lab-smoke:
	@set -euo pipefail; \
	for page in $(LAB_PAGES); do \
		test -s ${ROOT_DIR}/$$page || { echo "lab-smoke: $$page missing"; exit 1; }; \
		refs=$$(grep -o 'assets/[A-Za-z0-9._-]*' ${ROOT_DIR}/$$page | sort -u); \
		test -n "$$refs" || { echo "lab-smoke: $$page references no assets/ files"; exit 1; }; \
		for ref in $$refs; do \
			test -s "${ROOT_DIR}/$$ref" || { echo "lab-smoke: $$page references missing $$ref"; exit 1; }; \
		done; \
		case " $(LAB_WORKER_PAGES) " in \
			*" $$page "*) \
				worker=$$(for ref in $$(echo "$$refs" | grep '\.js$$'); do \
					grep -o 'worker-[A-Za-z0-9._-]*\.js' "${ROOT_DIR}/$$ref" || true; \
				done | sort -u | sed -n '1p'); \
				test -n "$$worker" || { echo "lab-smoke: $$page references no worker chunk from any of its js assets"; exit 1; }; \
				test -s "${ROOT_DIR}/assets/$$worker" || { echo "lab-smoke: worker chunk assets/$$worker missing"; exit 1; }; \
				;; \
			*) worker="no worker (static page)";; \
		esac; \
		echo "lab-smoke: $$page + $$(echo "$$refs" | wc -l | tr -d ' ') assets + $$worker OK"; \
	done

# Serve the gallery + vendored Orb Lab over HTTP. This is the way to *run*
# the site locally: the Lab's module worker will not load over file://, so
# `make open` (file:// in Chrome) previews the gallery only. Vendors the Lab
# first if lab.html is missing. Ctrl-C stops the server.
SITE_PORT ?= 8613
site:
	@set -euo pipefail; \
	missing=""; for page in $(LAB_PAGES); do [ -f ${ROOT_DIR}/$$page ] || missing=1; done; \
	[ -z "$$missing" ] || $(MAKE) -C ${ROOT_DIR} lab; \
	[ -d ${ROOT_DIR}/build/images/web ] \
		|| echo "note: build/images/web/ missing — gallery images need 'make cookie-cutters orbs bricks web-images'"; \
	( sleep 1; open "http://localhost:${SITE_PORT}/" ) & \
	echo "gallery  http://localhost:${SITE_PORT}/"; \
	echo "studio   http://localhost:${SITE_PORT}/studio.html"; \
	echo "orb lab  http://localhost:${SITE_PORT}/lab.html"; \
	echo "lego lab http://localhost:${SITE_PORT}/lego.html"; \
	echo "notes    http://localhost:${SITE_PORT}/design.html"; \
	echo "prints   http://localhost:${SITE_PORT}/prints.html"; \
	$(PYTHON) -m http.server ${SITE_PORT} --directory ${ROOT_DIR}

# Map of every user-facing experience and the target that starts it.
experiences:
	@echo "make site                  gallery + Orb Lab + Lego Lab, served at :${SITE_PORT} (this repo)"; \
	echo "make -C ${BIKAR_DIR} lab-dev     Orb Lab vite dev server w/ HMR at :4613 (bikar)"; \
	echo "make -C ${BIKAR_DIR} dev         Studio in Docker at :5173 (bikar)"; \
	echo "make -C ${BIKAR_DIR} local.dev   Studio vite dev server at :5173 (bikar, host)"; \
	echo "make start                 OpenSCAD app for cookie-cutter authoring (this repo)"

clean:
	rm -rf ${ROOT_DIR}/build/images/*.png
	rm -rf ${ROOT_DIR}/build/stls/*.stl
	rm -rf ${ROOT_DIR}/build/orb-views
	rm -rf ${ROOT_DIR}/build/.brick-names
	rm -f $(addprefix ${ROOT_DIR}/,$(LAB_PAGES))
	rm -rf ${ROOT_DIR}/assets

${DEP}:
	mkdir -f $$( dirname ${DEP} )
	git clone git@github.com:JustinSDK/dotSCAD.git ${DEP}

start: ${DEP}
	open -a "OpenSCAD"

open:
	open -a "Google Chrome" ${ROOT_DIR}/index.html

index_images:
	cat <(echo -n 'var data = ' ) <(ls -1 build/images/*.png | grep -v Common | jq -R '.' | jq -s ) > data.js

# Post-process raw renders into transparent, autocropped web images
# (build/images/web/) that the gallery uses. Requires pillow.
web-images:
	@command -v $(PYTHON) >/dev/null || { echo "no interpreter at '$(PYTHON)'"; exit 1; }
	@$(PYTHON) -c "import PIL" 2>/dev/null || { \
		echo "Pillow required, and $$($(PYTHON) -c 'import sys;print(sys.executable)') does not have it."; \
		echo "  install it there:  $(PYTHON) -m pip install pillow"; \
		echo "  or use one that does:  make $@ PYTHON=/path/to/python3"; \
		exit 1; }
	cd ${ROOT_DIR} && $(PYTHON) build/process_images.py

# Publish the static gallery to the gh-pages branch via a dedicated worktree,
# so master's working tree is never disturbed. gh-pages has a history that is
# intentionally separate from master; we sync the built site onto it.
#
# validate-site-graph runs FIRST, and is the only gate this target can rely on.
# `core.hooksPath` is repo-wide, so the pre-commit dispatchers do fire in the
# .gh-pages worktree — but that worktree tracks .githooks and not .claude, so
# every .claude-dependent gate skips itself there by design (validate-hooks is
# the regression test for that, and the 2026-08-02 deploy printed all three skip
# lines). This is therefore the one publish path with no gate in front of it,
# and site_graph.py's G4 rule — DEPLOY_PATHS and LAB_PAGES must agree with the
# nodes docs/site-graph.json marks `vendored` — is precisely a deploy-time
# invariant. Checking it here costs milliseconds and no network.
#
# build/stls also holds local slicer output (`bambu slice` writes .3mf, .gcode
# and result.json under build/stls/coupons/); no page links it, so it is
# stripped from the worktree after the copy and never reaches the public site.
deploy: validate-site-graph web-images lab prints-manifest status-manifest
	@set -euo pipefail; \
	cd ${ROOT_DIR}; \
	git show-ref --verify --quiet refs/heads/${PAGES_BRANCH} \
		|| { echo "branch ${PAGES_BRANCH} not found"; exit 1; }; \
	git worktree add -f ${PAGES_WORKTREE} ${PAGES_BRANCH}; \
	trap 'git worktree remove --force ${PAGES_WORKTREE} 2>/dev/null || true' EXIT; \
	for p in ${DEPLOY_PATHS}; do \
		rm -rf "${PAGES_WORKTREE}/$$p"; \
		mkdir -p "$$(dirname "${PAGES_WORKTREE}/$$p")"; \
		cp -R "$$p" "${PAGES_WORKTREE}/$$p"; \
	done; \
	find ${PAGES_WORKTREE} -name '.DS_Store' -not -path '*/.git/*' -delete; \
	find ${PAGES_WORKTREE}/build/stls -type f \( -name '*.gcode' -o -name '*.3mf' -o -name 'result.json' \) -delete; \
	cd ${PAGES_WORKTREE}; \
	git add -A; \
	if git diff --cached --quiet; then \
		echo "gh-pages already up to date"; \
	else \
		git commit -m "Deploy gallery from master ($$(git -C ${ROOT_DIR} rev-parse --short HEAD))"; \
		git push origin ${PAGES_BRANCH}; \
		echo "Deployed to ${PAGES_BRANCH}."; \
	fi

# The register prints.html reads: one record per docs/prints/<run>/, written by
# build/prints_manifest.py with the same frontmatter parser the prints gate uses.
# Gitignored and rebuilt by every deploy — and by every validate-prints, which
# depends on it — so nobody types a printed plate into existence and the
# generator's self-test (the gate's own fixture, plus a record it must refuse)
# runs before every write. An empty or absent docs/prints/ writes
# {"records": []}, which the page shows as the true state, not as an error.
prints-manifest:
	$(PYTHON) ${ROOT_DIR}/build/prints_manifest.py --self-test
	$(PYTHON) ${ROOT_DIR}/build/prints_manifest.py

# Branch guard — the wholesale form of .githooks/pre-commit.d/00-branch. The
# hook has no tree to check, so its wholesale form is its test: six scratch
# repos, the guard wired through the dispatcher, master and main refused by git
# and every other case landing. At the tail so no anchored line above moves.
validate-branch-guard:
	${ROOT_DIR}/.githooks/tests/refuse-main-commit.sh

# Schema-mirror gate: bikar vendors qiyas's exported JSON schemas byte-identical
# and generates its TypeScript from the copy, and nothing in either repo compares
# the two — so the mirror lagged qiyas by two stems (Scores' drop/surplus/
# max_drift, Contour's ribbon fields) with every check green. This reads both
# schema directories at the use-case map's pinned commits, offline, and names
# the def and fields that differ. `self-test` runs fixed fixtures, then a tempdir
# primary + linked worktree + siblings and requires the same failing verdict
# from both checkouts. Last in the file on purpose: every earlier target is a
# pinned `Makefile:L<n>` anchor somewhere, and inserting above moved five.
validate-schema-mirror:
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/schema_mirror.py --self-test
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/schema_mirror.py

# The register status.html reads: three facts about what the gallery was built
# from — the bikar commit (build/bikar-ref.txt), the use-case map's as_of pins,
# and the last deploy (the gh-pages tip). Written only by build/status_manifest.py,
# gitignored, and rebuilt by every deploy so nobody types a provenance into
# existence; the generator's self-test (pure parsers, a fixture repo on disk, and
# the by-design failures — a malformed stamp, a fresh clone with no gh-pages) runs
# before every write. Appended after validate-schema-mirror on purpose: it added
# no anchored line above it. D-049 §4.
status-manifest:
	$(PYTHON) ${ROOT_DIR}/build/status_manifest.py --self-test
	$(PYTHON) ${ROOT_DIR}/build/status_manifest.py

# Wholesale form of the status self-test — the check with no pre-commit hook
# behind it (hook_parity.py EXTRA), for the same reason validate-coupons has none:
# its three inputs are files other gates already own (bikar-ref.txt is gitignored,
# use-cases.md is gated by 20-use-cases, gh-pages is the deploy's own record), so
# there is no staged-file trigger to hang a hook on. It regenerates the manifest too.
validate-status: status-manifest

# Contract-mirror gate (hook 42): bikar and qiyas each vendor a prose copy of
# sacred-patterns' dsl-metadata-contract.md, header-stamped with the canonical
# version it was last vendored from. Nothing compared that header to canonical,
# so a mirror could sit a full amendment behind with every check green (the
# schema half is byte-checked by validate-schema-mirror; the prose is not). This
# reads canonical and both mirrors at each repo's default branch and names any
# mirror behind or dangling. Self-test first (fixtures + a primary/worktree/
# siblings layout asserting the same verdict), then the real check. Appended
# after validate-status for the same anchor reason as validate-schema-mirror.
validate-contract-mirror:
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/contract_mirror.py --self-test
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/contract_mirror.py

# Plan-sync gate (hook 43): docs/plan.md's §2 priority queue and §3 shipped log
# must move together. PS1 (every §3 `(2.N)` citation resolves to a §2 row) and
# PS2 (every §2 row carries a legal state mark) are resting invariants checked
# here over the whole tree; PS3 (a row moving into 🟢 requires a new §3 row in
# the same commit) is a diff and only the pre-commit hook sees it — see the
# gate docstring for why the resting form of the sync rule cries wolf at ~63%.
# Self-test first (a two-revision fixture: clean passes, every by-design failure
# fires), then the real resting check. Appended after validate-contract-mirror
# for the same anchor reason as validate-schema-mirror.
validate-plan-sync:
	$(PYTHON) ${ROOT_DIR}/.claude/gates/plan_sync.py --self-test
	$(PYTHON) ${ROOT_DIR}/.claude/gates/plan_sync.py

# --- Bambu X2D CLI (tools/bambu) -------------------------------------------
# BAMBU_DIR is the CLI package; runs need the repo-pinned Node on PATH (the
# system Node is too old — see tools/bambu/README.md and CLAUDE.md "Node").
BAMBU_DIR := ${ROOT_DIR}/tools/bambu

# Operator preflight: LAN/Developer-Mode reachable? token present? Studio +
# ffmpeg installed? X2D model accepted? This depends on the printer + local
# install, so it is a hand-run check, NOT part of `make validate` (which must
# pass with no hardware). `--probe-mcp` adds a live MCP handshake.
bambu-doctor:
	cd $(BAMBU_DIR) && npx tsx src/index.ts setup doctor

# Passively find the printer on the LAN before any config exists: listens for the
# X2D's own SSDP broadcast (receive-only — safe during an active print) and reports
# IP/serial/model + whether it's still cloud-bound. Hardware-dependent, so like
# bambu-doctor it is NOT part of `make validate`.
bambu-discover:
	cd $(BAMBU_DIR) && npx tsx src/index.ts setup discover

# Typecheck the CLI's TypeScript — the one gate the new tools/bambu code has no
# hook behind yet. Deliberately NOT a `bambu-validate` alias: mesh/plate/record
# validation are already first-class here (bikar's --check via the CLI's
# `validate mesh`; `coupons`/`validate-coupons` for the §7 table; the prints
# gate via `validate-prints` and the CLI's `validate record`), and re-wrapping
# them under a new name would fork one check into two paths that can disagree —
# the exact defect CLAUDE.md's robustness tenet forbids. Needs `npm install` in
# tools/bambu first.
bambu-typecheck:
	cd $(BAMBU_DIR) && npm run typecheck

# Constructions-ledger gate (hook 44): docs/constructions/ledger.md holds one row
# per GeoGebra construction on its way from a youtube reconstruction to a naqsh
# .bkr to a vendored coaster. The gate BLOCKS a row that names a .bkr bikar cannot
# resolve (via the sibling convention doc_pointers owns) or an src/Coasters/ STL
# not on disk, and a header pin youtube cannot resolve; it REPORTS (non-blocking)
# the youtube ids at the pin owed a row and the rows still saying "attempted" for
# a done id. youtube and bikar are read at a ref, never a working tree, so the
# verdict is checkout-independent (memory: gate-verdict-checkout-independent).
# `--self-test` builds a scratch youtube repo + a primary/worktree layout and
# requires every by-design failure to fire before the real run.
validate-constructions:
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/constructions_ledger.py --self-test
	BIKAR_DIR=$(BIKAR_DIR) $(PYTHON) ${ROOT_DIR}/.claude/gates/constructions_ledger.py

# Coasters — flat printable coasters that carry an inscribed GeoGebra
# construction, from the `coaster` declaration bikar added (umbrella plan
# P1.6/P2.7). Same shape as `bricks`, and same reason: a coaster has no
# per-symmetry-axis view set and no qiyas composite, so its gallery claim is
# the mesh itself, drawn by build/brick_previews.py --coasters via OpenSCAD
# import() where `make web-images` expects it.
#
# Two sizes per coaster, both RE-RENDERED from `--param size=` — never
# mesh-scaled (umbrella plan D-D): a 40 mm mini and a 90 mm standard, each
# `--check`ed on its own mesh. The standard is the gallery/download mesh and
# the vendored src/Coasters/<id>-coaster-standard.stl the constructions ledger
# points at; both sizes and the .bkr source are committed under src/Coasters/.
# An interlocked golden (`<id>-interlock-coaster.bkr`, D-069) rides the same
# glob and lands as id `<id>-interlock`; its preview is two tiles mated, because
# a single tile with tabs does not explain itself. A minimal golden
# (`<id>-minimal-coaster.bkr`, D-070) rides it too, as id `<id>-minimal`; its
# `--check` runs at the free-standing strap floor (CAL-CST-07), not the slab's.
# The two sizes are defined once here: the renders take them as `--param size=`
# and the preview pass takes the standard as the mate offset for an interlocked
# tile's two-tile picture (build/brick_previews.py --mate).
COASTER_MINI_MM := 40
COASTER_STANDARD_MM := 90
# The border band (D-071) is a mm knob that does NOT scale with `size` (design
# §7): the golden's default `border = 8` holds 7 chevrons on a 90 mm standard but
# starves a 40 mm mini, so the mini alone re-renders with a 4 mm band. Applied by a
# `case` on the id inside the loop, to the `*-border` goldens only — the plain,
# interlock and minimal goldens carry no `border` param and must not be passed one.
COASTER_MINI_BORDER_MM := 4
coasters: bikar-stamp
	@[ -f "$(BIKAR_DIR)/packages/cli/dist/index.js" ] \
		|| { echo "bikar CLI not built — run 'npm run build' in $(BIKAR_DIR)"; exit 1; }
	@ls $(BIKAR_DIR)/patterns/Constructions/*-coaster.bkr >/dev/null 2>&1 \
		|| { echo "no *-coaster.bkr in $(BIKAR_DIR)/patterns/Constructions — the coaster presets live on bikar's constructions work; override with 'make coasters BIKAR_DIR=...'"; exit 1; }
	@set -euo pipefail; \
	mkdir -p ${ROOT_DIR}/build/stls ${ROOT_DIR}/build/images ${ROOT_DIR}/src/Coasters; \
	: > ${ROOT_DIR}/build/.coaster-names; \
	for bkr in $(BIKAR_DIR)/patterns/Constructions/*-coaster.bkr; do \
		stem=$$(basename "$$bkr" .bkr); id=$${stem%-coaster}; \
		echo "== $$id"; \
		mini_extra=""; \
		case "$$id" in *-border) mini_extra="--param border=$(COASTER_MINI_BORDER_MM)" ;; esac; \
		$(BIKAR) render "$$bkr" --coaster Coaster --param size=$(COASTER_MINI_MM) $$mini_extra --format stl --check \
			-o ${ROOT_DIR}/src/Coasters/$$stem-mini.stl; \
		$(BIKAR) render "$$bkr" --coaster Coaster --param size=$(COASTER_STANDARD_MM) --format stl --check \
			-o ${ROOT_DIR}/src/Coasters/$$stem-standard.stl; \
		cp ${ROOT_DIR}/src/Coasters/$$stem-standard.stl ${ROOT_DIR}/build/stls/$$id.stl; \
		echo "$$id" >> ${ROOT_DIR}/build/.coaster-names; \
		cp "$$bkr" ${ROOT_DIR}/src/Coasters/; \
	done; \
	cd ${ROOT_DIR} && $(PYTHON) build/brick_previews.py --coasters --mate $(COASTER_STANDARD_MM)

# Encrypted-env gate — the wholesale form of .githooks/pre-commit.d/
# 11-env-encrypted. `.env` is commit-safe only while every value in it is
# `encrypted:…`; this checks every tracked .env* file's shape and runs the
# gate's own by-design failures (a plaintext value, the private key, a
# commented-out secret) so a green run means the gate was tested, not idle.
validate-env:
	@sh ${ROOT_DIR}/.claude/gates/check_env_encrypted.sh --self-test
	@cd ${ROOT_DIR} && sh .claude/gates/check_env_encrypted.sh

# bambu CLI flag reference. `bambu dump-flags` emits tools/bambu/FLAGS.md from the
# commander tree, so the reference cannot be wrong about a flag the way a hand-kept
# table drifts. `make bambu-flags` regenerates it; `validate-bambu-flags` (hook 45)
# self-tests the gate then diffs the checked-in copy, blocking a commit whose CLI
# surface moved without the reference. (D-0xx / task #11.)
bambu-flags:
	@cd $(BAMBU_DIR) && ./bin/bambu dump-flags --write

# A fresh worktree has no tools/bambu/node_modules; install them here rather than
# fail every `make validate` in a new worktree. The gate script itself still
# refuses to install, so a commit that never touches the CLI is not made to.
validate-bambu-flags:
	@[ -d ${ROOT_DIR}/tools/bambu/node_modules ] || npm ci --silent --prefix ${ROOT_DIR}/tools/bambu
	@sh ${ROOT_DIR}/.claude/gates/bambu_flags_gate.sh --self-test
	@cd ${ROOT_DIR} && sh .claude/gates/bambu_flags_gate.sh

# Session reflection (docs/session-reflection-design.md §9). The tool's own
# self-test, with its by-design "answer not taking" fixture, then an audit that
# every answered FAQ entry still shows falling recurrence. Not in `validate`
# yet: it reads this machine's transcripts, and the FAQ has nothing answered.
validate-reflect:
	$(PYTHON) $(ROOT_DIR)/tools/session_reflect.py census --self-test
	$(PYTHON) $(ROOT_DIR)/tools/session_reflect.py show --audit


# Id-clash gate — the wholesale form of .githooks/pre-commit.d/46-decision-ids.
# Self-tests tools/next_id.py on a throwaway repo (a stale id, a rebased id, an
# id another branch claims, a duplicate), then checks the working tree against
# origin/master. Take a new D-/Q- id with `python3 tools/next_id.py next D`.
validate-ids:
	$(PYTHON) $(ROOT_DIR)/tools/next_id.py --self-test
	$(PYTHON) $(ROOT_DIR)/tools/next_id.py check
