# https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_OpenSCAD_in_a_command_line_environment
# https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html

SHELL := /bin/bash
ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

# Default openscad lib path: https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Libraries
DEP := ${HOME}/Documents/OpenSCAD/libraries/dotSCAD
# Resolve the OpenSCAD binary across install variants (versioned app, plain app, PATH).
openscad := $(shell \
	for c in \
		/Applications/OpenSCAD-*.app/Contents/MacOS/OpenSCAD \
		/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD \
		$$(command -v openscad); do \
		[ -x "$$c" ] && echo "$$c" && break; \
	done)

# Orbs — 3D-printable Islamic geometric orbs generated by the bikar DSL
# engine (sibling repo). Source of truth is bikar's patterns/Orbs/*.bkr;
# `make orbs` compiles each to a watertight STL (--check runs the
# print-readiness mesh gate), renders its per-symmetry-axis validation
# views, and styles a hero view into a gallery preview PNG. The .bkr
# sources are copied into src/Orbs/ so the gallery's Source links resolve
# in this repo.
BIKAR_DIR := ${HOME}/Workspace/git/bikar
BIKAR := node $(BIKAR_DIR)/packages/cli/dist/index.js
ORB_VIEWS := $(ROOT_DIR)/build/orb-views

# gh-pages deploy
PAGES_BRANCH := gh-pages
PAGES_WORKTREE := $(ROOT_DIR)/.gh-pages
# Recursively expanded, not `:=`, because LAB_PAGES is defined further down
# beside the vendor step that uses it. `:=` here would expand to nothing and
# deploy a gallery with no studio pages in it.
DEPLOY_PATHS = index.html $(LAB_PAGES) assets build/images build/stls src LICENSE README.md

.PHONY: cookie-cutters orbs bricks lab lego-lab lab-vendor lab-smoke web-images deploy setup-hooks site experiences validate-use-cases validate-docs validate-hooks validate-site-graph site-graph

# One-time per clone: route git hooks to the tracked .githooks/ dir
# (pre-commit dispatches .githooks/pre-commit.d/: gitleaks secret scan,
# the use-case map guard — see .claude/skills/maintain-use-cases/ — then the
# design-doc gate, see .claude/gates/docs_gate.py; then the site-graph gate,
# see .claude/gates/site_graph.py).
setup-hooks:
	git -C ${ROOT_DIR} config core.hooksPath .githooks
	@echo "hooks: core.hooksPath -> .githooks"
	@echo "  pre-commit.d = gitleaks (staged hunks) + use-cases + docs-gate + site-graph"
	@echo "  pre-push     = gitleaks full history (this repo has no CI)"
	@if ! command -v gitleaks >/dev/null 2>&1; then \
		echo "  WARNING: gitleaks not installed — commits AND pushes will block."; \
		echo "           brew install gitleaks   (override: GITLEAKS_OK=1)"; \
	fi

# Validate the actor/use-case map's hash-pinned code pointers.
validate-use-cases:
	@python3 -c "import yaml" 2>/dev/null || { echo "PyYAML required: pip install pyyaml"; exit 1; }
	python3 ${ROOT_DIR}/.claude/skills/maintain-use-cases/validate.py

# Design-doc gate: dead relative links (D1/K9), validators shipped without
# asserted PASS+FAIL examples (D2/K6), defaults with no citation or CAL-* bet
# id (D3/K4). Rules and the measurement behind them:
# docs/grounding-defect-taxonomy.md. `self-test` runs the gate's own fixtures.
validate-docs:
	python3 ${ROOT_DIR}/.claude/gates/docs_gate.py --self-test
	python3 ${ROOT_DIR}/.claude/gates/docs_gate.py

# `core.hooksPath` is repo-wide, so pre-commit.d/ runs in every worktree of this
# clone — including the `.gh-pages` one `deploy` creates, which tracks .githooks
# and not .claude. This builds that shape and asserts each hook skips instead of
# dying; it is the regression test for a deploy that failed on the gh-pages
# commit with `[Errno 2] No such file or directory`.
validate-hooks:
	${ROOT_DIR}/.githooks/tests/worktree-without-claude.sh

# Site-graph gate: docs/site-graph.json declares every page this project
# publishes, every link between them, and each host's exposure. The gate holds
# that declaration to the repo. It never asks whether a URL resolves — four
# crawler runs on 2026-08-02 reported the one real defect as green, because
# Cloudflare Access answers an unauthenticated request with HTTP 200. Reasoning:
# docs/site-graph.md; survey: docs/research/sitemap-link-graph-survey.md.
# `self-test` mutates the real graph in memory and requires each defect to fire.
validate-site-graph:
	BIKAR_DIR=$(BIKAR_DIR) python3 ${ROOT_DIR}/.claude/gates/site_graph.py --self-test
	BIKAR_DIR=$(BIKAR_DIR) python3 ${ROOT_DIR}/.claude/gates/site_graph.py

# Regenerate the ```mermaid block in docs/site-graph.md from the JSON, then
# re-check — so a hand-edited render cannot outlive the graph it renders.
site-graph:
	python3 ${ROOT_DIR}/.claude/gates/site_graph.py --update-doc
	$(MAKE) -C ${ROOT_DIR} validate-site-graph

%.png: %.scad
	@echo Generating $*.png from $@
	${openscad} -o ${ROOT_DIR}/build/images/$$(basename $*.png) $*.scad

%.stl: %.scad
	@echo Generating $*.stl from $@
	${openscad} -o ${ROOT_DIR}/build/stls/$$(basename $*.stl) $*.scad

cookie-cutters:
	ls ${ROOT_DIR}/src/CookieCutters/*.scad | sed 's/.scad//g' | grep -v Common \
		| xargs -n 1 basename \
		| xargs -n 1 bash -c ' \
			cd ${ROOT_DIR}/src/CookieCutters && make -f ${ROOT_DIR}/Makefile $${0}.png $${0}.stl \
		'
orbs:
	@[ -f "$(BIKAR_DIR)/packages/cli/dist/index.js" ] \
		|| { echo "bikar CLI not built — run 'npm run build' in $(BIKAR_DIR)"; exit 1; }
	@command -v rsvg-convert >/dev/null \
		|| { echo "rsvg-convert required: brew install librsvg"; exit 1; }
	@set -euo pipefail; \
	mkdir -p ${ROOT_DIR}/build/stls ${ROOT_DIR}/build/images ${ROOT_DIR}/src/Orbs; \
	for bkr in $(BIKAR_DIR)/patterns/Orbs/*.bkr; do \
		stem=$$(basename "$$bkr" .bkr); name=$${stem//-/}; \
		echo "== $$name"; \
		$(BIKAR) render "$$bkr" --format stl --check -o ${ROOT_DIR}/build/stls/$$name.stl; \
		mkdir -p $(ORB_VIEWS)/$$name; \
		$(BIKAR) render "$$bkr" --format views -o $(ORB_VIEWS)/$$name; \
		cp "$$bkr" ${ROOT_DIR}/src/Orbs/; \
	done; \
	cd ${ROOT_DIR} && python3 build/orb_previews.py

# Bricks — LEGO-compatible pieces from the same bikar engine (Lego Lab
# design §10 P0). Same shape as `orbs`, with one difference that is worth
# stating: an orb's preview comes from its per-symmetry-axis validation
# views, and a brick has none — there is no brick view set and no recorded
# qiyas composite, so a brick's claim is made by its two grid gates and the
# mesh gate, not by a render. build/brick_previews.py therefore draws the
# mesh itself, via OpenSCAD import(), which lands gold-on-cream exactly
# where `make web-images` expects it.
bricks:
	@[ -f "$(BIKAR_DIR)/packages/cli/dist/index.js" ] \
		|| { echo "bikar CLI not built — run 'npm run build' in $(BIKAR_DIR)"; exit 1; }
	@[ -d "$(BIKAR_DIR)/patterns/Lego" ] \
		|| { echo "no patterns/Lego in $(BIKAR_DIR) — the brick presets live on bikar's lego-lab work; override with 'make bricks BIKAR_DIR=...'"; exit 1; }
	@set -euo pipefail; \
	mkdir -p ${ROOT_DIR}/build/stls ${ROOT_DIR}/build/images ${ROOT_DIR}/src/Lego; \
	: > ${ROOT_DIR}/build/.brick-names; \
	for bkr in $(BIKAR_DIR)/patterns/Lego/*.bkr; do \
		stem=$$(basename "$$bkr" .bkr); name=$${stem//-/}; \
		echo "== $$name"; \
		$(BIKAR) render "$$bkr" --format stl --check -o ${ROOT_DIR}/build/stls/$$name.stl; \
		echo "$$name" >> ${ROOT_DIR}/build/.brick-names; \
		cp "$$bkr" ${ROOT_DIR}/src/Lego/; \
	done; \
	cd ${ROOT_DIR} && python3 build/brick_previews.py

# The studio — the pages built by bikar's packages/lab (vite) and vendored
# here at the site root, plus the hashed assets/ dir they share. All
# generated, gitignored on master, published by `make deploy`.
#
# One build serves all of them, because each is one of packages/lab's *entries*
# and not a package of its own (Lego Lab design §9). That is also why there is
# one vendor step rather than four: four builds would mean four `rm -rf assets`,
# and each would delete the chunks the previous page had just been linked
# against. `lab` and `lego-lab` are the two names people reach for; they
# share the recipe so `make lab lego-lab` still builds once.
#
# The page list lives here once. It is the deploy-side twin of the catalogue
# bikar checks against its own directory (Lego Lab design §13) — this end
# cannot read that one, so a page added there and not here vendors nothing and
# `lab-smoke` never looks for it. Adding a page is two edits, in two repos, and
# saying so is cheaper than a cross-repo check that would have to run a build.
LAB_PAGES = studio.html lab.html lego.html design.html
# The subset that runs the compile worker. studio.html and design.html render
# from static data, so requiring a worker chunk of them would fail a page that
# is working exactly as designed.
LAB_WORKER_PAGES = lab.html lego.html

lab lego-lab: lab-vendor

lab-vendor:
	@for page in $(LAB_PAGES); do \
		[ -f "$(BIKAR_DIR)/packages/lab/$$page" ] \
			|| { echo "no packages/lab/$$page in $(BIKAR_DIR) — the studio entries live on bikar's lego-lab work; override with 'make lab BIKAR_DIR=...'"; exit 1; }; \
	done
	@set -euo pipefail; \
	cd $(BIKAR_DIR)/packages/lab && npx vite build; \
	for page in $(LAB_PAGES); do \
		cp $(BIKAR_DIR)/packages/lab/dist/$$page ${ROOT_DIR}/$$page; \
	done; \
	rm -rf ${ROOT_DIR}/assets; \
	cp -R $(BIKAR_DIR)/packages/lab/dist/assets ${ROOT_DIR}/assets; \
	$(MAKE) -C ${ROOT_DIR} lab-smoke; \
	echo "Studio vendored: $(LAB_PAGES) + assets/"

# Vendoring smoke (orb-lab-p2-design §4.2): each vendored page and its hashed
# assets must exist and reference each other — a broken copy step or a stale
# assets/ dir fails here, not on the deployed site. Every page is checked,
# because they share one assets/ dir and a rebuild that re-hashed only one
# page's chunks would leave the others pointing at files that no longer exist.
#
# The worker hunt reads *every* js asset a page pulls in, not the first one
# alphabetically. The old version took the first and got away with it only
# while the entry chunk happened to sort first; adding studio/design chunks
# moved a shared chunk to the front and the check failed a page that was
# perfectly well-formed. "First by name" was never the entry module.
lab-smoke:
	@set -euo pipefail; \
	for page in $(LAB_PAGES); do \
		test -s ${ROOT_DIR}/$$page || { echo "lab-smoke: $$page missing"; exit 1; }; \
		refs=$$(grep -o 'assets/[A-Za-z0-9._-]*' ${ROOT_DIR}/$$page | sort -u); \
		test -n "$$refs" || { echo "lab-smoke: $$page references no assets/ files"; exit 1; }; \
		for ref in $$refs; do \
			test -s "${ROOT_DIR}/$$ref" || { echo "lab-smoke: $$page references missing $$ref"; exit 1; }; \
		done; \
		case " $(LAB_WORKER_PAGES) " in \
			*" $$page "*) \
				worker=$$(for ref in $$(echo "$$refs" | grep '\.js$$'); do \
					grep -o 'worker-[A-Za-z0-9._-]*\.js' "${ROOT_DIR}/$$ref" || true; \
				done | sort -u | sed -n '1p'); \
				test -n "$$worker" || { echo "lab-smoke: $$page references no worker chunk from any of its js assets"; exit 1; }; \
				test -s "${ROOT_DIR}/assets/$$worker" || { echo "lab-smoke: worker chunk assets/$$worker missing"; exit 1; }; \
				;; \
			*) worker="no worker (static page)";; \
		esac; \
		echo "lab-smoke: $$page + $$(echo "$$refs" | wc -l | tr -d ' ') assets + $$worker OK"; \
	done

# Serve the gallery + vendored Orb Lab over HTTP. This is the way to *run*
# the site locally: the Lab's module worker will not load over file://, so
# `make open` (file:// in Chrome) previews the gallery only. Vendors the Lab
# first if lab.html is missing. Ctrl-C stops the server.
SITE_PORT ?= 8613
site:
	@set -euo pipefail; \
	missing=""; for page in $(LAB_PAGES); do [ -f ${ROOT_DIR}/$$page ] || missing=1; done; \
	[ -z "$$missing" ] || $(MAKE) -C ${ROOT_DIR} lab; \
	[ -d ${ROOT_DIR}/build/images/web ] \
		|| echo "note: build/images/web/ missing — gallery images need 'make cookie-cutters orbs bricks web-images'"; \
	( sleep 1; open "http://localhost:${SITE_PORT}/" ) & \
	echo "gallery  http://localhost:${SITE_PORT}/"; \
	echo "studio   http://localhost:${SITE_PORT}/studio.html"; \
	echo "orb lab  http://localhost:${SITE_PORT}/lab.html"; \
	echo "lego lab http://localhost:${SITE_PORT}/lego.html"; \
	echo "notes    http://localhost:${SITE_PORT}/design.html"; \
	python3 -m http.server ${SITE_PORT} --directory ${ROOT_DIR}

# Map of every user-facing experience and the target that starts it.
experiences:
	@echo "make site                  gallery + Orb Lab + Lego Lab, served at :${SITE_PORT} (this repo)"; \
	echo "make -C ${BIKAR_DIR} lab-dev     Orb Lab vite dev server w/ HMR at :4613 (bikar)"; \
	echo "make -C ${BIKAR_DIR} dev         Studio in Docker at :5173 (bikar)"; \
	echo "make -C ${BIKAR_DIR} local.dev   Studio vite dev server at :5173 (bikar, host)"; \
	echo "make start                 OpenSCAD app for cookie-cutter authoring (this repo)"

clean:
	rm -rf ${ROOT_DIR}/build/images/*.png
	rm -rf ${ROOT_DIR}/build/stls/*.stl
	rm -rf ${ROOT_DIR}/build/orb-views
	rm -rf ${ROOT_DIR}/build/.brick-names
	rm -f $(addprefix ${ROOT_DIR}/,$(LAB_PAGES))
	rm -rf ${ROOT_DIR}/assets

${DEP}:
	mkdir -f $$( dirname ${DEP} )
	git clone git@github.com:JustinSDK/dotSCAD.git ${DEP}

start: ${DEP}
	open -a "OpenSCAD"

open:
	open -a "Google Chrome" ${ROOT_DIR}/index.html

index_images:
	cat <(echo -n 'var data = ' ) <(ls -1 build/images/*.png | grep -v Common | jq -R '.' | jq -s ) > data.js

# Post-process raw renders into transparent, autocropped web images
# (build/images/web/) that the gallery uses. Requires pillow.
web-images:
	@command -v python3 >/dev/null || { echo "python3 required"; exit 1; }
	@python3 -c "import PIL" 2>/dev/null || { echo "Pillow required: pip install pillow"; exit 1; }
	cd ${ROOT_DIR} && python3 build/process_images.py

# Publish the static gallery to the gh-pages branch via a dedicated worktree,
# so master's working tree is never disturbed. gh-pages has a history that is
# intentionally separate from master; we sync the built site onto it.
deploy: web-images lab
	@set -euo pipefail; \
	cd ${ROOT_DIR}; \
	git show-ref --verify --quiet refs/heads/${PAGES_BRANCH} \
		|| { echo "branch ${PAGES_BRANCH} not found"; exit 1; }; \
	git worktree add -f ${PAGES_WORKTREE} ${PAGES_BRANCH}; \
	trap 'git worktree remove --force ${PAGES_WORKTREE} 2>/dev/null || true' EXIT; \
	for p in ${DEPLOY_PATHS}; do \
		rm -rf "${PAGES_WORKTREE}/$$p"; \
		mkdir -p "$$(dirname "${PAGES_WORKTREE}/$$p")"; \
		cp -R "$$p" "${PAGES_WORKTREE}/$$p"; \
	done; \
	find ${PAGES_WORKTREE} -name '.DS_Store' -not -path '*/.git/*' -delete; \
	cd ${PAGES_WORKTREE}; \
	git add -A; \
	if git diff --cached --quiet; then \
		echo "gh-pages already up to date"; \
	else \
		git commit -m "Deploy gallery from master ($$(git -C ${ROOT_DIR} rev-parse --short HEAD))"; \
		git push origin ${PAGES_BRANCH}; \
		echo "Deployed to ${PAGES_BRANCH}."; \
	fi
