# https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_OpenSCAD_in_a_command_line_environment
# https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html

SHELL := /bin/bash
ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

# Default openscad lib path: https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Libraries
DEP := ${HOME}/Documents/OpenSCAD/libraries/dotSCAD
# Resolve the OpenSCAD binary across install variants (versioned app, plain app, PATH).
openscad := $(shell \
	for c in \
		/Applications/OpenSCAD-*.app/Contents/MacOS/OpenSCAD \
		/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD \
		$$(command -v openscad); do \
		[ -x "$$c" ] && echo "$$c" && break; \
	done)

# Orbs — 3D-printable Islamic geometric orbs generated by the bikar DSL
# engine (sibling repo). Source of truth is bikar's patterns/Orbs/*.bkr;
# `make orbs` compiles each to a watertight STL (--check runs the
# print-readiness mesh gate), renders its per-symmetry-axis validation
# views, and styles a hero view into a gallery preview PNG. The .bkr
# sources are copied into src/Orbs/ so the gallery's Source links resolve
# in this repo.
BIKAR_DIR := ${HOME}/Workspace/git/bikar
BIKAR := node $(BIKAR_DIR)/packages/cli/dist/index.js
ORB_VIEWS := $(ROOT_DIR)/build/orb-views

# gh-pages deploy
PAGES_BRANCH := gh-pages
PAGES_WORKTREE := $(ROOT_DIR)/.gh-pages
DEPLOY_PATHS := index.html lab.html assets build/images build/stls src LICENSE README.md

.PHONY: cookie-cutters orbs lab lab-smoke web-images deploy setup-hooks

# One-time per clone: route git hooks to the tracked .githooks/ dir
# (pre-commit runs a gitleaks secret scan on staged changes).
setup-hooks:
	git -C ${ROOT_DIR} config core.hooksPath .githooks
	@echo "hooks: core.hooksPath -> .githooks (pre-commit = gitleaks)"

%.png: %.scad
	@echo Generating $*.png from $@
	${openscad} -o ${ROOT_DIR}/build/images/$$(basename $*.png) $*.scad

%.stl: %.scad
	@echo Generating $*.stl from $@
	${openscad} -o ${ROOT_DIR}/build/stls/$$(basename $*.stl) $*.scad

cookie-cutters:
	ls ${ROOT_DIR}/src/CookieCutters/*.scad | sed 's/.scad//g' | grep -v Common \
		| xargs -n 1 basename \
		| xargs -n 1 bash -c ' \
			cd ${ROOT_DIR}/src/CookieCutters && make -f ${ROOT_DIR}/Makefile $${0}.png $${0}.stl \
		'
orbs:
	@[ -f "$(BIKAR_DIR)/packages/cli/dist/index.js" ] \
		|| { echo "bikar CLI not built — run 'npm run build' in $(BIKAR_DIR)"; exit 1; }
	@command -v rsvg-convert >/dev/null \
		|| { echo "rsvg-convert required: brew install librsvg"; exit 1; }
	@set -euo pipefail; \
	mkdir -p ${ROOT_DIR}/build/stls ${ROOT_DIR}/build/images ${ROOT_DIR}/src/Orbs; \
	for bkr in $(BIKAR_DIR)/patterns/Orbs/*.bkr; do \
		stem=$$(basename "$$bkr" .bkr); name=$${stem//-/}; \
		echo "== $$name"; \
		$(BIKAR) render "$$bkr" --format stl --check -o ${ROOT_DIR}/build/stls/$$name.stl; \
		mkdir -p $(ORB_VIEWS)/$$name; \
		$(BIKAR) render "$$bkr" --format views -o $(ORB_VIEWS)/$$name; \
		cp "$$bkr" ${ROOT_DIR}/src/Orbs/; \
	done; \
	cd ${ROOT_DIR} && python3 build/orb_previews.py

# Orb Lab — the knob-driven orb configurator built by bikar's packages/lab
# (vite). `make lab` builds it there and vendors the output here: lab.html
# at the site root (the gallery links to it) plus its hashed assets/ dir.
# Both are generated, gitignored on master, and published by `make deploy`.
lab:
	@set -euo pipefail; \
	cd $(BIKAR_DIR)/packages/lab && npx vite build; \
	cp $(BIKAR_DIR)/packages/lab/dist/lab.html ${ROOT_DIR}/lab.html; \
	rm -rf ${ROOT_DIR}/assets; \
	cp -R $(BIKAR_DIR)/packages/lab/dist/assets ${ROOT_DIR}/assets; \
	$(MAKE) -C ${ROOT_DIR} lab-smoke; \
	echo "Orb Lab vendored: lab.html + assets/"

# Vendoring smoke (orb-lab-p2-design §4.2): the vendored page and its hashed
# assets must exist and reference each other — a broken copy step or a stale
# assets/ dir fails here, not on the deployed site.
lab-smoke:
	@set -euo pipefail; \
	test -s ${ROOT_DIR}/lab.html || { echo "lab-smoke: lab.html missing"; exit 1; }; \
	refs=$$(grep -o 'assets/[A-Za-z0-9._-]*' ${ROOT_DIR}/lab.html | sort -u); \
	test -n "$$refs" || { echo "lab-smoke: lab.html references no assets/ files"; exit 1; }; \
	for ref in $$refs; do \
		test -s "${ROOT_DIR}/$$ref" || { echo "lab-smoke: lab.html references missing $$ref"; exit 1; }; \
	done; \
	main=$$(echo "$$refs" | grep '\.js$$' | head -1); \
	worker=$$(grep -o 'worker-[A-Za-z0-9._-]*\.js' "${ROOT_DIR}/$$main" | sort -u | head -1); \
	test -n "$$worker" || { echo "lab-smoke: $$main references no worker chunk"; exit 1; }; \
	test -s "${ROOT_DIR}/assets/$$worker" || { echo "lab-smoke: worker chunk assets/$$worker missing"; exit 1; }; \
	echo "lab-smoke: lab.html + $$(echo "$$refs" | wc -l | tr -d ' ') assets + $$worker OK"

clean:
	rm -rf ${ROOT_DIR}/build/images/*.png
	rm -rf ${ROOT_DIR}/build/stls/*.stl
	rm -rf ${ROOT_DIR}/build/orb-views
	rm -rf ${ROOT_DIR}/lab.html ${ROOT_DIR}/assets

${DEP}:
	mkdir -f $$( dirname ${DEP} )
	git clone git@github.com:JustinSDK/dotSCAD.git ${DEP}

start: ${DEP}
	open -a "OpenSCAD"

open:
	open -a "Google Chrome" ${ROOT_DIR}/index.html

index_images:
	cat <(echo -n 'var data = ' ) <(ls -1 build/images/*.png | grep -v Common | jq -R '.' | jq -s ) > data.js

# Post-process raw renders into transparent, autocropped web images
# (build/images/web/) that the gallery uses. Requires pillow.
web-images:
	@command -v python3 >/dev/null || { echo "python3 required"; exit 1; }
	@python3 -c "import PIL" 2>/dev/null || { echo "Pillow required: pip install pillow"; exit 1; }
	cd ${ROOT_DIR} && python3 build/process_images.py

# Publish the static gallery to the gh-pages branch via a dedicated worktree,
# so master's working tree is never disturbed. gh-pages has a history that is
# intentionally separate from master; we sync the built site onto it.
deploy: web-images lab
	@set -euo pipefail; \
	cd ${ROOT_DIR}; \
	git show-ref --verify --quiet refs/heads/${PAGES_BRANCH} \
		|| { echo "branch ${PAGES_BRANCH} not found"; exit 1; }; \
	git worktree add -f ${PAGES_WORKTREE} ${PAGES_BRANCH}; \
	trap 'git worktree remove --force ${PAGES_WORKTREE} 2>/dev/null || true' EXIT; \
	for p in ${DEPLOY_PATHS}; do \
		rm -rf "${PAGES_WORKTREE}/$$p"; \
		mkdir -p "$$(dirname "${PAGES_WORKTREE}/$$p")"; \
		cp -R "$$p" "${PAGES_WORKTREE}/$$p"; \
	done; \
	find ${PAGES_WORKTREE} -name '.DS_Store' -not -path '*/.git/*' -delete; \
	cd ${PAGES_WORKTREE}; \
	git add -A; \
	if git diff --cached --quiet; then \
		echo "gh-pages already up to date"; \
	else \
		git commit -m "Deploy gallery from master ($$(git -C ${ROOT_DIR} rev-parse --short HEAD))"; \
		git push origin ${PAGES_BRANCH}; \
		echo "Deployed to ${PAGES_BRANCH}."; \
	fi
