// `bambu dump-flags` — the CLI describes its own surface, and a gate diffs it.
//
// The commander tree (name, description, positional args, options) IS the source of truth for every
// flag. Hand-written prose (README, the bambu skill) drifts the moment a `.option()` is added; a
// second hand-maintained copy is exactly the "defensible argument that management is occurring" the
// repo's issue-register-evaluation warns against. So instead we EMIT the reference from the live tree
// and check it in as FLAGS.md; hook 45-bambu-flags regenerates and blocks a commit whose FLAGS.md
// drifted. Add a flag, forget to regenerate → the diff is the reminder (repo tenet: "the tool prints
// the number, the gate diffs it", same shape as counts_gate.py).
//
// Determinism is the whole contract: the output must depend only on the registered tree, in
// registration order, so a clean tree regenerates byte-identical FLAGS.md and the gate is silent.

import type { Command } from "commander";

/** First line of a (possibly multi-line) description — the table cell wants the summary, not the
 *  whole help paragraph. Pipes are escaped so a description never breaks the markdown table. */
function firstLine(text: string | undefined): string {
  const line = (text ?? "").split("\n")[0]!.trim();
  return line.replace(/\|/g, "\\|");
}

/** One command's section: heading (full path), description, positional args, then options. A command
 *  with neither args nor options (a pure group like `bambu slice`) still gets a heading + description
 *  so the reference lists every verb the CLI answers to. */
function section(path: string, cmd: Command): string {
  const lines: string[] = [`### \`${path}\``];
  const desc = firstLine(cmd.description());
  if (desc) lines.push("", desc);

  const args = cmd.registeredArguments ?? [];
  if (args.length > 0) {
    lines.push("", "| Argument | Required | Description |", "|---|---|---|");
    for (const a of args) {
      const req = a.required ? "yes" : "no";
      lines.push(`| \`${a.name()}${a.variadic ? "…" : ""}\` | ${req} | ${firstLine(a.description)} |`);
    }
  }

  // `.options` excludes the auto -h/--help; a hidden option (`.hidden`) is left out of the reference
  // exactly as it is out of --help, so the doc mirrors what a user can actually see.
  const opts = cmd.options.filter((o) => !o.hidden);
  if (opts.length > 0) {
    lines.push("", "| Flag | Description |", "|---|---|");
    for (const o of opts) {
      lines.push(`| \`${o.flags}\` | ${firstLine(o.description)} |`);
    }
  }
  return lines.join("\n");
}

/** Depth-first walk in registration order, skipping hidden commands (they are absent from --help too,
 *  and the reference documents the visible surface). Yields [fullPath, command] pairs. */
function* walk(cmd: Command, prefix: string): Generator<[string, Command]> {
  for (const sub of cmd.commands) {
    // commander marks a hidden command with `_hidden`; there is no public getter, so read it defensively.
    if ((sub as unknown as { _hidden?: boolean })._hidden) continue;
    const path = `${prefix} ${sub.name()}`;
    yield [path, sub];
    yield* walk(sub, path);
  }
}

/** Render the whole registered program to the FLAGS.md body. Deterministic given the tree. */
export function dumpFlags(program: Command): string {
  const root = program.name();
  const header = [
    `<!-- GENERATED by \`${root} dump-flags\` — do not edit by hand. Regenerate with \`make bambu-flags\`. -->`,
    "",
    `# \`${root}\` CLI — flag reference`,
    "",
    "Every subcommand, positional argument, and option the CLI exposes, generated from the commander",
    "tree. Hook `45-bambu-flags` blocks a commit whose checked-in copy drifted from this — add a flag,",
    `run \`make bambu-flags\`. Live help stays authoritative per verb: \`${root} <group> <verb> --help\`.`,
    "",
  ];

  // Root-level global options (e.g. --version) first, so the reference is complete top-down.
  const rootOpts = program.options.filter((o) => !o.hidden);
  if (rootOpts.length > 0) {
    header.push(`### \`${root}\` (global)`, "", "| Flag | Description |", "|---|---|");
    for (const o of rootOpts) header.push(`| \`${o.flags}\` | ${firstLine(o.description)} |`);
    header.push("");
  }

  const sections: string[] = [];
  for (const [path, cmd] of walk(program, root)) {
    sections.push(section(path, cmd));
  }
  // One blank line between every block, and a trailing newline (a POSIX text file ends in one, and
  // `git diff --exit-code` in the gate is byte-exact).
  return [header.join("\n"), sections.join("\n\n")].join("\n") + "\n";
}
