#!/usr/bin/env python3
"""What each filament costs: the store's price for every coaster line and color, and a refresh.

`docs/design/coaster/themes/catalog/prices.yaml` holds a price per kilogram for each filament line
(what `bambu plates by-color --costs` turns grams into dollars with) and, per color, its product
code, price and whether it is in stock. This script reads them off the store's own product pages
and says what changed since the file was written.

Each Bambu US product page carries its variants as structured data (a JSON-LD `ProductGroup`): one
entry per color and kind, named "PLA Basic - Black (10101) / Refill / 1kg", with a price and a
stock flag. The 10-roll floor is printed on the page as "$11.19 USD /roll (Lowest price for 10+
rolls)" beside "MSRP: $15.99"; the MSRP says which kind the floor belongs to, so it is read, not
worked out from a discount.

Usage:
    prices.py refresh            fetch every page, print the prices and what changed; writes nothing
    prices.py refresh --write    the same, then write prices.yaml
    prices.py --self-test

Other brands later (D-105): a store is an entry in STORES with a reader. Bambu US is the only one.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
import urllib.request
from collections import Counter
from pathlib import Path

import yaml

SKILL = Path(__file__).resolve().parent.parent
ROOT = SKILL.parent.parent.parent
CATALOG_DIR = ROOT / "docs" / "design" / "coaster" / "themes" / "catalog"
PRICES = CATALOG_DIR / "prices.yaml"
CATALOG = CATALOG_DIR / "catalog.yaml"

# The product page for each line a coaster can print in (catalog.py's COASTER_LINES), as the
# store's sitemap (us.store.bambulab.com/sitemap_products_1.xml) listed them on 2026-10-05. The
# key is the store's own line name, which is what prices.yaml is keyed by. PLA Lite, PLA Tough
# and PLA Dynamic have no page there; plain PLA Silk is gone (its page is a 404).
STORES = {
    "bambu-us": {
        "name": "Bambu Lab US store",
        "base": "https://us.store.bambulab.com/products/",
        "pages": {
            "PLA Basic": "pla-basic-filament",
            "PLA Basic Gradient": "pla-basic-gradient",
            "PLA Matte": "pla-matte",
            "PLA Silk+": "pla-silk-upgrade",
            "PLA Silk Multi-Color": "pla-silk-multi-color",
            "PLA Sparkle": "pla-sparkle",
            "PLA Galaxy": "pla-galaxy",
            "PLA Marble": "pla-marble",
            "PLA Metal": "pla-metal",
            "PLA Translucent": "pla-translucent",
            "PLA Glow": "pla-glow",
            "PLA Wood": "pla-wood",
            "PLA Pure": "pla-pure",
            "PLA Tough+": "pla-tough-upgrade",
            "PLA Aero": "pla-aero",
            "PLA-CF": "pla-cf",
            "PETG Basic": "petg-basic",
            "PETG Matte": "petg-matte",
            "PETG HF": "petg-hf",
            "PETG Translucent": "petg-translucent",
        },
    },
}
STORE = "bambu-us"

# The kind words a variant name uses, and the tier each one prices.
KINDS = {"refill": "refill", "filament with spool": "spool"}
TEN = {"refill": "ten_refill", "spool": "ten_spool"}

# PETG pages write "Black(30105)" with no space before the code, so the space is optional.
VARIANT = re.compile(r"^(?P<product>.+?) - (?P<color>.+?) ?\((?P<code>\d{5})\)(?P<rest>(?: / [^/]+)*)$")
WEIGHT = re.compile(r"^(?P<n>\d+(?:\.\d+)?)\s*(?P<unit>kg|g)$", re.I)
LD_JSON = re.compile(r'<script[^>]*application/ld\+json[^>]*>(.*?)</script>', re.S)
FLOOR = re.compile(r"\$(?P<floor>\d+\.\d\d)(?:</span>)?(?:<span[^>]*>)?\s*USD\s*(?:</span>)*\s*"
                   r"(?:</span>)?\s*<span[^>]*>/roll \(Lowest price for 10\+ rolls\)</span>"
                   r".{0,400}?MSRP: \$(?P<msrp>\d+\.\d\d)", re.S)

HEADER = """\
# generated by .claude/skills/color-themes/scripts/prices.py refresh --write; do not edit.
# What each filament costs, in US dollars per kilogram, as {store} showed it on {read}:
# every coaster line's product page, read from the variants the page lists as structured data.
#
# `bambu plates by-color --costs` turns a plate's grams into dollars with `lines`. A line not
# listed has no price, and its plates show grams with no dollars rather than a guessed price.
#
# Each line has up to four prices. A price left out was not on the page, so it is not filled in by
# arithmetic: the cost view falls back to the spool price and says so.
#   refill:     one refill bought on its own (no spool)
#   spool:      one roll with its spool
#   ten_refill: a refill when 10 or more rolls are bought at once, as the page prints it
#   ten_spool:  a roll with spool at the 10-roll price, when that is the kind the page prints it for
# A line's refill or spool price is the one most of its colors sell at; `colors` has each one.
# The 10-roll price is called a sale with no end date (docs/research/2026-10-04-coaster-pricing.md),
# so refresh before trusting an old file.
#
# `colors` is keyed by Bambu's product code, the code catalog.yaml uses. Each has the store's line,
# its name, the price of each kind sold, and the kinds out of stock. A code missing here is not on
# sale in this store. Gradient and multi-color spools are their own lines here (PLA Basic Gradient,
# PLA Silk Multi-Color) while catalog.yaml files them under PLA Basic and PLA Silk.
"""


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (3d-models prices.py)"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8", "replace")


def product_group(html: str) -> dict | None:
    for m in LD_JSON.finditer(html):
        try:
            d = json.loads(m.group(1))
        except json.JSONDecodeError:
            continue
        if isinstance(d, dict) and d.get("@type") == "ProductGroup":
            return d
    return None


def per_kg(rest: str) -> tuple[str | None, float | None]:
    """' / Refill / 1kg' -> ('refill', 1.0). Unknown kind or weight -> None for that part."""
    kind, kg = None, None
    for part in (p.strip() for p in rest.split("/") if p.strip()):
        if part.lower() in KINDS:
            kind = KINDS[part.lower()]
        elif m := WEIGHT.match(part):
            n = float(m["n"])
            kg = n if m["unit"].lower() == "kg" else n / 1000
    return kind, kg


def read_page(line: str, html: str) -> dict:
    """One product page -> {colors: {code: {...}}, floor, msrp, skipped: [variant names]}."""
    group = product_group(html)
    if group is None:
        return {"line": line, "colors": {}, "floor": None, "msrp": None, "skipped": [],
                "error": "no ProductGroup on the page"}
    colors: dict[str, dict] = {}
    skipped = []
    for v in group.get("hasVariant", []):
        name = v.get("name", "")
        m = VARIANT.match(name)
        offer = v.get("offers") or {}
        kind, kg = per_kg(m["rest"]) if m else (None, None)
        price = offer.get("price")
        if not m or kind is None or not kg or price is None or offer.get("priceCurrency") != "USD":
            skipped.append(name)
            continue
        c = colors.setdefault(m["code"], {"line": line, "name": m["color"].strip()})
        c[kind] = round(float(price) / kg, 2)
        if not str(offer.get("availability", "")).endswith("InStock"):
            c.setdefault("out_of_stock", []).append(kind)
    floor = FLOOR.search(html)
    return {"line": line, "colors": colors, "skipped": skipped,
            "floor": float(floor["floor"]) if floor else None,
            "msrp": float(floor["msrp"]) if floor else None}


def most_common(values: list[float]) -> float | None:
    if not values:
        return None
    count = Counter(values).most_common()
    best = max(n for _, n in count)
    return max(v for v, n in count if n == best)  # a tie goes to the dearer price, never the cheaper


def line_prices(page: dict) -> tuple[dict, list[str]]:
    """A page's colors -> the line's prices and notes on anything uneven."""
    out, notes = {}, []
    for kind in ("refill", "spool"):
        vals = [c[kind] for c in page["colors"].values() if kind in c]
        p = most_common(vals)
        if p is None:
            continue
        out[kind] = p
        if len(set(vals)) > 1:
            notes.append(f"{page['line']}: {kind} prices differ by color "
                         f"({', '.join(f'${v:.2f}' for v in sorted(set(vals)))}); the line uses ${p:.2f}")
    if page["floor"] is not None:
        kind = next((k for k in ("refill", "spool") if out.get(k) == page["msrp"]), None)
        if kind:
            out[TEN[kind]] = page["floor"]
        else:
            notes.append(f"{page['line']}: a 10-roll price ${page['floor']:.2f} against MSRP "
                         f"${page['msrp']:.2f}, which is neither its refill nor its spool price; left out")
    return out, notes


def build(pages: dict[str, dict], read: str) -> tuple[dict, list[str]]:
    lines, colors, notes = {}, {}, []
    for line, page in pages.items():
        if page.get("error"):
            notes.append(f"{line}: {page['error']}")
            continue
        lp, n = line_prices(page)
        notes += n
        if page["skipped"]:
            notes.append(f"{line}: {len(page['skipped'])} variant(s) not read: {page['skipped'][:3]}")
        if lp:
            lines[line] = lp
        for code, c in page["colors"].items():
            if code in colors:
                notes.append(f"{code}: on two pages ({colors[code]['line']}, {line}); kept the first")
                continue
            colors[code] = c
    doc = {"read": read, "store": STORE, "source": STORES[STORE]["base"],
           "lines": lines, "colors": dict(sorted(colors.items()))}
    return doc, notes


def same_name(store: str, catalog: str) -> bool:
    """The store's short name for a color the catalog names longer counts as the same: it drops a
    line word in front ("Gray" for "Translucent Gray") and a note behind ("Velvet Eclipse" for
    "Velvet Eclipse (Black-Red)"), and spells Grey for Gray."""
    s, c = (n.lower().replace("grey", "gray").strip() for n in (store, catalog))
    c = re.sub(r"\s*\(.*\)$", "", c)
    return s == c or c.endswith(" " + s)


def against_catalog(doc: dict, catalog: dict) -> list[str]:
    """Store codes the catalog lacks, and names that differ. The line is not compared: the store
    files gradient and multi-color spools under their own lines."""
    known = {e["code"]: e for e in catalog["colors"]}
    out = []
    for code, c in doc["colors"].items():
        e = known.get(code)
        if e is None:
            out.append(f"{code} {c['line']} {c['name']}: on sale, not in catalog.yaml (run catalog.py refresh)")
        elif not same_name(c["name"], e["name"]):
            out.append(f"{code}: the store calls it {c['name']!r}, the catalog {e['name']!r}")
    return out


def diff(old: dict | None, new: dict) -> list[str]:
    if not old:
        return ["no prices.yaml yet"]
    out = []
    ol, nl = old.get("lines", {}), new["lines"]
    for line in sorted(set(ol) | set(nl)):
        a, b = ol.get(line, {}), nl.get(line, {})
        if not a:
            out.append(f"+ {line}: {fmt(b)}")
        elif not b:
            out.append(f"- {line}: {fmt(a)} (no price read now)")
        else:
            for t in sorted(set(a) | set(b)):
                if a.get(t) != b.get(t):
                    out.append(f"~ {line} {t}: {money(a.get(t))} -> {money(b.get(t))}")
    oc, nc = old.get("colors", {}), new["colors"]
    added, gone = sorted(set(nc) - set(oc)), sorted(set(oc) - set(nc))
    if oc:  # the first file with colors has nothing to compare them with
        out += [f"+ {k} {nc[k]['line']} {nc[k]['name']}: now on sale" for k in added]
        out += [f"- {k} {oc[k]['line']} {oc[k]['name']}: no longer on sale" for k in gone]
        for k in sorted(set(oc) & set(nc)):
            a, b = oc[k].get("out_of_stock", []), nc[k].get("out_of_stock", [])
            if a != b:
                out.append(f"~ {k} {nc[k]['name']}: out of stock {a or 'none'} -> {b or 'none'}")
    return out


def money(v) -> str:
    return "none" if v is None else f"${v:.2f}"


def fmt(p: dict) -> str:
    return ", ".join(f"{t} {money(v)}" for t, v in p.items())


def text(doc: dict) -> str:
    head = HEADER.format(store=STORES[doc["store"]]["name"], read=doc["read"])
    body = {"read": doc["read"], "store": doc["store"], "source": doc["source"]}
    out = head + "\n" + yaml.safe_dump(body, sort_keys=False)
    out += "\nlines:\n"
    width = max(len(k) for k in doc["lines"]) + 1
    for line, p in doc["lines"].items():
        inner = ", ".join(f"{t}: {v:.2f}" for t, v in p.items())
        out += f"  {(line + ':').ljust(width)} {{ {inner} }}\n"
    out += "\ncolors:\n"
    for code, c in doc["colors"].items():
        fields = [f"line: {json.dumps(c['line'])}", f"name: {json.dumps(c['name'])}"]
        fields += [f"{t}: {c[t]:.2f}" for t in ("refill", "spool") if t in c]
        if c.get("out_of_stock"):
            fields.append(f"out_of_stock: [{', '.join(c['out_of_stock'])}]")
        out += f"  '{code}': {{ {', '.join(fields)} }}\n"
    return out


def load(path: Path):
    if not path.exists():
        return None
    with open(path) as f:
        return yaml.safe_load(f)


def refresh(write: bool) -> int:
    store = STORES[STORE]
    pages = {}
    for line, handle in store["pages"].items():
        url = store["base"] + handle
        try:
            pages[line] = read_page(line, fetch(url))
        except OSError as e:
            pages[line] = {"line": line, "error": f"{url}: {e}"}
    doc, notes = build(pages, dt.date.today().isoformat())
    print(f"{store['name']}, read {doc['read']}: {len(doc['lines'])} lines, {len(doc['colors'])} colors")
    for line, p in doc["lines"].items():
        print(f"  {line:22} {fmt(p)}")
    for n in notes + against_catalog(doc, load(CATALOG)):
        print(f"note: {n}")
    changes = diff(load(PRICES), doc)
    print("changed since prices.yaml:" if changes else "nothing changed since prices.yaml")
    for c in changes:
        print(f"  {c}")
    if any(p.get("error") for p in pages.values()):
        print("a page could not be read; nothing written", file=sys.stderr)
        return 1
    if write:
        PRICES.write_text(text(doc))
        print(f"wrote {PRICES.relative_to(ROOT)}")
    return 0


# --- self-test -------------------------------------------------------------------------------

def page_fixture(variants: list[tuple[str, float, bool]], floor: tuple[float, float] | None) -> str:
    group = {"@context": "https://schema.org/", "@type": "ProductGroup", "name": "X",
             "hasVariant": [{"@type": "Product", "name": n,
                             "offers": {"@type": "Offer", "priceCurrency": "USD", "price": p,
                                        "availability": "https://schema.org/" + ("InStock" if s else "OutOfStock")}}
                            for n, p, s in variants]}
    html = f'<script type="application/ld+json">{json.dumps(group)}</script>'
    if floor:
        html += ('<div><span class="a"><span>$%.2f</span><span class="hidden"> USD</span></span>'
                 '<span class="b">/roll (Lowest price for 10+ rolls)</span></div><div><span class="c">'
                 '<span>MSRP: $%.2f</span></span></div>' % floor)
    return html


def self_test() -> int:
    fails = []

    def check(name, got, want):
        if got != want:
            fails.append(f"{name}: got {got!r}, want {want!r}")

    basic = read_page("PLA Basic", page_fixture([
        ("PLA Basic - Black (10101) / Refill / 1kg", 15.99, True),
        ("PLA Basic - Black (10101) / Filament with spool / 1kg", 18.99, True),
        ("PLA Basic - Red (10200) / Refill / 1kg", 15.99, False),
        ("PLA Basic - Jade White (10100) / Refill / 1kg", 17.99, True),
        ("PLA Basic - Sample (10999) / Refill / 0.5kg", 9.00, True),
        ("PLA Basic Starter Pack", 49.00, True),
        ("PLA Basic - Orange(10300) / Refill / 1kg", 15.99, True),
    ], (11.19, 15.99)))
    check("colors read", sorted(basic["colors"]), ["10100", "10101", "10200", "10300", "10999"])
    check("half kilo is per kg", basic["colors"]["10999"]["refill"], 18.0)
    check("out of stock kept", basic["colors"]["10200"].get("out_of_stock"), ["refill"])
    check("no code skipped", basic["skipped"], ["PLA Basic Starter Pack"])
    lp, notes = line_prices(basic)
    check("line refill is the common price", lp.get("refill"), 15.99)
    check("ten tier from the MSRP", lp.get("ten_refill"), 11.19)
    check("uneven prices noted", any("differ by color" in n for n in notes), True)

    # The Silk+ case: the floor's MSRP is the spool price, so it is the spool's 10-roll price.
    silk = read_page("PLA Silk+", page_fixture([
        ("PLA Silk+ - Gold (13405) / Refill / 1kg", 15.99, True),
        ("PLA Silk+ - Gold (13405) / Filament with spool / 1kg", 18.99, True),
    ], (13.29, 18.99)))
    lp, _ = line_prices(silk)
    check("silk+ ten_spool", (lp.get("ten_spool"), "ten_refill" in lp), (13.29, False))

    # A floor whose MSRP matches neither price is left out, never assigned.
    odd = read_page("PLA Odd", page_fixture([("PLA Odd - Blue (10601) / Refill / 1kg", 15.99, True)],
                                            (9.99, 21.00)))
    lp, notes = line_prices(odd)
    check("odd floor left out", ("ten_refill" in lp, any("left out" in n for n in notes)), (False, True))

    # Spool only, no floor: no refill price is made up.
    sparkle = read_page("PLA Sparkle", page_fixture([
        ("PLA Sparkle - Onyx Black (13700) / Filament with spool / 1kg", 24.99, True)], None))
    check("spool only", line_prices(sparkle)[0], {"spool": 24.99})

    check("no product data", read_page("PLA Silk", "<html>404</html>").get("error"), "no ProductGroup on the page")

    doc, _ = build({"PLA Basic": basic, "PLA Sparkle": sparkle}, "2026-10-05")
    again = yaml.safe_load(text(doc))
    check("file round-trips", (again["lines"], again["colors"]), (doc["lines"], doc["colors"]))

    old = {"lines": {"PLA Basic": {"refill": 14.99, "spool": 18.99}, "PETG Basic": {"refill": 13.99}},
           "colors": {"10101": {"line": "PLA Basic", "name": "Black"}, "10400": {"line": "PLA Basic", "name": "Yellow"}}}
    d = diff(old, doc)
    for want in ["~ PLA Basic refill: $14.99 -> $15.99", "- PETG Basic: refill $13.99 (no price read now)",
                 "+ PLA Sparkle: spool $24.99", "- 10400 PLA Basic Yellow: no longer on sale",
                 "+ 13700 PLA Sparkle Onyx Black: now on sale"]:
        check(f"diff has {want!r}", want in d, True)
    check("unchanged reads as unchanged", diff(again, doc), [])

    cat = {"colors": [{"code": "10101", "name": "Black"}, {"code": "10100", "name": "Jade White"}]}
    found = against_catalog(doc, cat)
    check("a code the catalog lacks is named", any(f.startswith("10200 ") for f in found), True)
    check("matching names pass", any(f.startswith("10101") for f in found), False)
    check("short names match", [same_name("Gray", "Translucent Gray"), same_name("Blue Grey", "Blue Gray"),
                                same_name("Velvet Eclipse", "Velvet Eclipse (Black-Red)")], [True, True, True])
    check("a different color does not", same_name("Gray", "Dark Gray Blue"), False)

    if fails:
        print("prices.py self-test FAILED:")
        for f in fails:
            print(f"  {f}")
        return 1
    print("prices.py self-test: ok")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--self-test", action="store_true")
    sub = ap.add_subparsers(dest="cmd")
    r = sub.add_parser("refresh", help="fetch the store's prices and say what changed")
    r.add_argument("--write", action="store_true", help="also write prices.yaml")
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    if args.cmd == "refresh":
        return refresh(args.write)
    ap.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
